### ISSUE TITLE
The mobile search playlist will show that the load failed.

### ISSUE THREAD

**Issue by yanindulge** [lyswhut/lx-music-mobile#10]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[例如：Android 10]
  -软件安装包及版本：[例如：1.0.0 arm64-v8a]

**其他内容**

**Comment by lyswhut** [comment]
Please provide steps to reproduce the behavior, if possible, please attach a screenshot

**Comment by yanindulge** [comment]
> 请提供复制行为的步骤，如果可能，请附上截图。

1. Open NetEase Cloud and click on the playlist.
2. Copy the playlist link. 
3. Switch the software playlist platform after opening the software. 
4. Import playlist links. 
5. Display load failed


I don't know how to attach screenshots.

**Comment by yanindulge** [comment]
![C90763510059555449A2D5624ED12E23](https://user-images.githubusercontent.com/84668296/119264618-844eef00-bc16-11eb-8275-6332fb005d09.jpg)
![CB65027A97F8D5710F1DC472F9CB4763](https://user-images.githubusercontent.com/84668296/119264622-89ac3980-bc16-11eb-8df7-0475c6166af4.jpg)
![A0929E5924D7797183EAD145B1375F72](https://user-images.githubusercontent.com/84668296/119264628-8c0e9380-bc16-11eb-8ed7-f0d78387bb17.jpg)


> 请提供复制行为的步骤，如果可能，请附上截图。

![C90763510059555449A2D5624ED12E23](https://user-images.githubusercontent.com/84668296/119264638-9761bf00-bc16-11eb-8c2f-59eeea54d4b0.jpg)
![CB65027A97F8D5710F1DC472F9CB4763](https://user-images.githubusercontent.com/84668296/119264640-992b8280-bc16-11eb-9806-69992d5efaca.jpg)
![A0929E5924D7797183EAD145B1375F72](https://user-images.githubusercontent.com/84668296/119264643-9af54600-bc16-11eb-9c79-8c4b2657da88.jpg)

**Comment by yanindulge** [comment]
> > 请提供复制行为的步骤，如果可能，请附上截图。
 ![C90763510059555449A2D5624ED12E23](https://user-images.githubusercontent.com/84668296/119264618-844eef00-bc16-11eb-8275-6332fb005d09.jpg)
> ![CB65027A97F8D5710F1DC472F9CB4763](https://user-images.githubusercontent.com/84668296/119264622-89ac3980-bc16-11eb-8df7-0475c6166af4.jpg)
> ![A0929E5924D7797183EAD145B1375F72](https://user-images.githubusercontent.com/84668296/119264628-8c0e9380-bc16-11eb-8ed7-f0d78387bb17.jpg)

**Comment by lyswhut** [comment]
Open the playlist only supports links and IDs, you need to remove the content that does not belong to links or IDs
