### ISSUE TITLE
[Bug]: 小米11，miui13.0.5不兼容

### ISSUE THREAD

**Issue by sdhzwc** [lyswhut/lx-music-mobile#101]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

能够正常运行即可

### 实际行为

无法安装
![lADPJx8ZvwiyDKrNDIDNBaA_1440_3200 jpg_720x720q90g](https://user-images.githubusercontent.com/46134044/161196075-4d1825c1-9005-44d7-8cc9-41d6268a4995.jpg)
 

### Lx Music 版本

v0.11.1

### 操作系统版本

安卓12

**Comment by lyswhut** [comment]
下错安装包了吧

**Comment by sdhzwc** [comment]
> 下错安装包了吧



> 下错安装包了吧

![image](https://user-images.githubusercontent.com/46134044/161371154-370e8b66-3a81-48ab-b640-2dad3730b7de.png)
我使用这两个都不好使，最后在百度找了一个包好使了
