### ISSUE TITLE
[Bug]: 非循环模式下播放完全结束后，直接按播放按钮，无法开始新播放

### ISSUE THREAD

**Issue by garywill** [lyswhut/lx-music-mobile#104]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在 

- 顺序播放
- 单曲不循环播放 

模式下，播放完成结束后，直接按播放按钮，可以开始新的播放

- 从列表头部开始播放
- 再播放一次单曲

### 实际行为

按播放按钮后，只播放了一个2s的无声内容

### Lx Music 版本

0.11.1

### 操作系统版本

9

**Comment by lyswhut** [comment]
已在v0.12.0修复

**Comment by garywill** [comment]
感谢作者修复！
刚刚试了，还有一点问题：
1. 单曲不循环播放过程中，如果按了上一曲、下一曲，那么界面上的播放暂停键会失效，只有在下拉通知中才能暂停
2. 单曲不循环播放完成后，无法从下拉通知中按播放。

**Comment by lyswhut** [comment]
> 感谢作者修复！ 刚刚试了，还有一点问题：
> 
> 1. 单曲不循环播放过程中，如果按了上一曲、下一曲，那么界面上的播放暂停键会失效，只有在下拉通知中才能暂停
> 2. 单曲不循环播放完成后，无法从下拉通知中按播放。

我这么没能重现这个问题
