### ISSUE TITLE
桌面歌词调到最大显示还是比较小，希望加入个自定义大小填字体大小数值的

### ISSUE THREAD

**Issue by cmf866** [lyswhut/lx-music-mobile#107]
桌面歌词大小，希望加入个自定义数值大小，因为手机互联投屏到车机，现在歌词最大界面，在车屏幕上显示还是比较小；顺便加入本地音乐导入播放就更好了

**Comment by lyswhut** [comment]
根据现在的大小来看，你觉得最大值要设置要多大合适？

**Comment by cmf866** [comment]
意思如果增加一个自定义数值就好，自己根据自己车机适合的进行填列数值




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-mobile] 桌面歌词调到最大显示还是比较小，希望加入个自定义大小填字体大小数值的 (Issue #107)





 
根据现在的大小来看，你觉得最大值要设置要多大合适？

**Comment by lyswhut** [comment]
这个目前没有改成手动输入的打算

**Comment by cmf866** [comment]
最大增加到500吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-mobile] 桌面歌词调到最大显示还是比较小，希望加入个自定义大小填字体大小数值的 (Issue #107)





 
这个目前没有改成手动输入的打算

**Comment by cmf866** [comment]
大神，是否考虑增加下本地音乐播放功能，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyswhut/lx-music-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyswhut/lx-music-mobile] 桌面歌词调到最大显示还是比较小，希望加入个自定义大小填字体大小数值的 (Issue #107)





 
这个目前没有改成手动输入的打算

**Comment by lyswhut** [comment]
已在v1.21.0新增，本地音乐暂不考虑
