### ISSUE TITLE
[Bug]: statusbar-lyric分支版本运行出现空指针异常

### ISSUE THREAD

**Issue by ftevxk** [lyswhut/lx-music-mobile#109]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常播放运行

### 实际行为

![3fbc2d34d983d0607a46076691fcb07](https://user-images.githubusercontent.com/9601413/164470769-06389704-03c0-4860-84ba-a4ad377ed8d2.jpg)
第一次出现问题后每次播放必现

### Lx Music 版本

0.12.0-sl arm64-v8a

### 最后正常的版本

0.12.0 arm64-v8a

### 操作系统版本

Android 12

**Comment by ftevxk** [comment]
回忆了一下流程是正在播放音乐，使用备份软件强杀了播放器，再打开一点击播放就报错，现在在播放之前在设置切换一次桌面歌词再切换回状态栏歌词恢复正常。

**Comment by lyswhut** [comment]
不懂啥情况下为什么没设置歌词就播放了，可以尝试清理缓存试试，刚加了个防止崩溃的判断
