### ISSUE TITLE
应用启动失败

### ISSUE THREAD

**Issue by onenovice** [lyswhut/lx-music-mobile#11]
**截图**
![Screenshot_20210524_092539_cn.toside.music.mobile.jpg](https://user-images.githubusercontent.com/37800761/119284471-5d260b00-bc72-11eb-9310-9882e558c398.jpg)

**环境：**
  -操作系统及版本：[例如：Android 10]
  -软件安装包及版本：[例如：1.0.0 arm64-v8a]

**Comment by lyswhut** [comment]
能正常运行的最后一次做了什么操作呢？
这个问题看起来是软件启动时尝试恢复上一次播放的歌曲时出现了异常，如果能提供重现步骤那可以有助于我更快的修复这个问题。

对于这个问题，目前的解决方案有：
1. 等待软件更新修复这个问题；
2. 清理软件的所有数据，但是这将会丢失你收藏的歌曲

**Comment by onenovice** [comment]
出bug前导入了网易歌单
清除数据后恢复

**Comment by lyswhut** [comment]
此问题应该在v0.3.3得到修复，再发生此问题会出现提示，并将相关信息记录到错误日志中
