### ISSUE TITLE
希望新增歌詞 簡體轉繁體 的功能

### ISSUE THREAD

**Issue by WZZan** [lyswhut/lx-music-mobile#114]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望新增歌詞 簡體轉繁體 的功能

### 描述你想要的解决方案

希望新增歌詞 簡體轉繁體 的功能

**Comment by lyswhut** [comment]
已在v0.13.0新增，已知的问题：开关桌面歌词时，当前播放的歌曲桌面歌词可能不会马上转繁体，下版本修复
