### ISSUE TITLE
[Feature]: react-native-track-player包依赖

### ISSUE THREAD

**Issue by a153884673** [lyswhut/lx-music-mobile#116]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

react-native-track-player这个包依赖一直下载不下来

### 描述你想要的解决方案

下载依赖

**Comment by a153884673** [comment]
看到说要配置代理，我使用了 官方源，淘宝源，cnpm ，yarn，tyarn等都下载不下来，请问什么源可以下载吗

**Comment by lyswhut** [comment]
将npm更新到8.5.x的最新版本：
https://github.com/lyswhut/lx-music-mobile/blob/5d00d81b436f142528a7e301c4d88d2bbd18fa3a/.github/workflows/release.yml#L45

**Comment by a153884673** [comment]
十分感谢
