### ISSUE TITLE
[Bug]: 搜索多个歌曲之后会出现奇怪的Bug

### ISSUE THREAD

**Issue by 2096779623** [lyswhut/lx-music-mobile#118]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

之前搜索过的歌曲不会出现在搜索列表中。

### 实际行为

![Screenshot_20220522-195553](https://user-images.githubusercontent.com/57583560/169694103-976c40ef-98f9-4aec-8515-d87bf136c22a.png)

如果搜索歌曲会跑到下面

![Screenshot_20220522-195755](https://user-images.githubusercontent.com/57583560/169694124-fa257aeb-a08c-4a34-8f55-00a1127e60ac.png)

### Lx Music 版本

0.13.0 arm64-v8a

### 操作系统版本

Android 10

### 附加信息

重启软件之后就没了

**Comment by lyswhut** [comment]
我这边没能重现你说的问题，详细操作步骤说一下

**Comment by lerdertre** [comment]
1.搜索一首歌后点击输入框右边的❌，有概率会出现如图一的情况（测试10次出现4次）
2.搜索一首歌然后把输入框内的内容删掉再输入其他内容也会出现（测试10次出现3次）

目前我发现清空搜索结果的方法是点到设置栏再点回来（也许会有其他方法），歌单，排行榜，播放列表均不行
设备：Android 10 Redmi K30 洛雪：0.14.0-beta
![Screenshot_2022-06-05-22-22-06-688_cn toside music mobile](https://user-images.githubusercontent.com/62736171/172056136-465f34ff-1a49-46ee-b903-dbc1676f94b8.jpg)
![Screenshot_2022-06-05-22-21-57-613_cn toside music mobile](https://user-images.githubusercontent.com/62736171/172056142-1343e533-b781-46e9-a6ad-9eb9786852e7.jpg)

**Comment by lyswhut** [comment]
我大概知道了，这个看起来是搜索列表中存在重复的歌曲id导致的，切到设置页、用返回键返回桌面再进应该也可以清空搜索结果，晚点我会处理下

**Comment by lerdertre** [comment]
ok

**Comment by lyswhut** [comment]
修复已包含在beta2中，你们可以去这里下载最新的beta构建试试：
https://github.com/lyswhut/lx-music-mobile/actions/workflows/beta-pack.yml

**Comment by lyswhut** [comment]
已在v0.14.0修复
