### ISSUE TITLE
状态栏歌词不支持滚动

### ISSUE THREAD

**Issue by ljwrnd** [lyswhut/lx-music-mobile#120]
![3349b52efe2901fa6416b201f53bcee](https://user-images.githubusercontent.com/97397870/169776442-33944cc4-80b7-4006-ac1b-59e03572f98b.jpg)

**Comment by ljwrnd** [comment]
这个就是普通版本 设置不了滚动 要是能滚动就会方便很多

**Comment by ljwrnd** [comment]
> 你这个用的是状态栏歌词模块的版本吧？ 滚动是要在模块里设置。 不过我现在已经用回普通版本了，也挺好的

这个就是普通版本 设置不了滚动 要是能滚动就会方便很多

**Comment by ljwrnd** [comment]
> > > 你这个用的是状态栏歌词模块的版本吧？ 滚动是要在模块里设置。 不过我现在已经用回普通版本了，也挺好的
> > 
> > 
> > 这个就是普通版本 设置不了滚动 要是能滚动就会方便很多
> 
> 具体是歌词的动效支持吧

横着滚动
![346ac42baec3cfdbeea5538d425242c](https://user-images.githubusercontent.com/97397870/169779884-695b7392-6a44-45cb-bd38-ae52b5fcb039.jpg)
就是唱到哪 歌词就在框里滚动显示到哪

**Comment by lyswhut** [comment]
已在v0.14.0新增
