### ISSUE TITLE
[Feature]: 添加网易云我喜欢歌单的添加方式

### ISSUE THREAD

**Issue by Meteor666s** [lyswhut/lx-music-mobile#122]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

电脑端的我喜欢可以通过token的方式添加，希望手机端也可以实现

### 描述你想要的解决方案

电脑端的我喜欢可以通过token的方式添加，希望手机端也可以实现

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-mobile/issues/51
