### ISSUE TITLE
增加歌曲分享功能

### ISSUE THREAD

**Issue by yewuxue** [lyswhut/lx-music-mobile#13]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by jy05568536** [comment]
最好别弄什么分享、用户体系什么的，静静的本地使用不好么

**Comment by ptrzs3** [comment]
我是洛雪音乐安卓端的用户，我觉得楼主的意思可能是增加生成歌曲海报的功能，洛雪是我在手机端的主力音乐APP，但是当我遇到好听的歌曲想要分享时，还需要打开酷狗来生成海报。如果能添加生成歌词海报的话，就更好了^_^

**Comment by ameaninglessname** [comment]
如果可以分享 确实不错

**Comment by yewuxue** [comment]
> 最好别弄什么分享、用户体系什么的，静静的本地使用不好么

你说的是软件内部分享，我说的是分享到weixin朋友圈这样的

**Comment by yewuxue** [comment]
> 我是洛雪音乐安卓端的用户，我觉得楼主的意思可能是增加生成歌曲海报的功能，洛雪是我在手机端的主力音乐APP，但是当我遇到好听的歌曲想要分享时，还需要打开酷狗来生成海报。如果能添加生成歌词海报的话，就更好了^_^

没毛病

**Comment by ameaninglessname** [comment]
> 这个目前不打算添加

我看桌面端有【歌曲详情页】的按钮，移动端有类似的功能么？
我需要的分享功能 指的就是 一个链接就够了，
如果移动端也有这个功能，我可以获取到歌曲链接，就能在其它地方分享了
能一键复制，或者是 【歌曲】【歌手】【链接】的格式的话，就更方便了

**Comment by lyswhut** [comment]
> 我看桌面端有【歌曲详情页】的按钮，移动端有类似的功能么？ 我需要的分享功能 指的就是 一个链接就够了， 如果移动端也有这个功能，我可以获取到歌曲链接，就能在其它地方分享了 能一键复制，或者是 【歌曲】【歌手】【链接】的格式的话，就更方便了

这个可以加，你可以提供一个模板看看

**Comment by ameaninglessname** [comment]
【《凡人修仙传》 第41话 魔道争锋20-哔哩哔哩国创】https://b23.tv/ep471418
【《千从狩》 第10话 家属探望日·家人-哔哩哔哩国创】https://b23.tv/ep471468

上面的格式：
[剧名][标题][来源][链接]

个人感觉b站的分享链接还行，
主要的思路就是，包含歌曲的关键信息，方便直接分享或者二次编辑

**Comment by lyswhut** [comment]
已在v0.12.0添加，虽然分享出去的歌曲链接不一定能播放（可能需要vip）
