### ISSUE TITLE
安卓车机安装时报错：安装包解析失败[Bug]: 

### ISSUE THREAD

**Issue by gemingjun123** [lyswhut/lx-music-mobile#134]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望可以出个车机版，适配安卓低版本系统，音乐软件在车上用的频率应该是最多的

### 实际行为

安装高德等乱七八糟的软件没问题，安装洛雪就解析失败，我也不知道是什么原因

### Lx Music 版本

所有的版本都试过了

### 操作系统版本

安卓5.0

**Comment by wsqryt** [comment]
车机系统4.3、4.4的比较多，只能等待适配版本了

**Comment by wsqryt** [comment]
我也很期待4.3、4.4的车机版

**Comment by Gao-le-le** [comment]
> ### 解决方案检查
> * [x]  我已阅读常见问题(https://lyswhut.github.io/lx-music-doc/mobile/faq)，并没有找到解决方案[x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-mobile/issues?utf8=%E2%9C%93&q=))，并没有发现类似的问题
> 
> ### 预期行为
> 希望可以出个车机版，适配安卓低版本系统，音乐软件在车上用的频率应该是最多的
> 
> ### 实际行为
> 安装高德等乱七八糟的软件没问题，安装洛雪就解析失败，我也不知道是什么原因
> 
> ### Lx Music 版本
> 所有的版本都试过了
> 
> ### 最后正常的版本
> _No response_
> 
> ### 操作系统版本
> 安卓5.0
> 
> ### 附加信息
> _No response_

我也是安装包解析失败，这个有解决吗
