### ISSUE TITLE
[Feature]: 跪求兼容安卓4.3

### ISSUE THREAD

**Issue by gemingjun123** [lyswhut/lx-music-mobile#139]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

跪求兼容安卓4.3，车机是安卓4.3，安装报错，解析安装包失败

### 描述你想要的解决方案

兼容安卓4.3

**Comment by lyswhut** [comment]
由于框架限制，无法安卓5以下的版本，此问题无法解决
