### ISSUE TITLE
发现的三处不太合理之处，提出来一下

### ISSUE THREAD

**Issue by ufuf-2346** [lyswhut/lx-music-mobile#15]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述错误**
1、从后台划掉APP时音乐依然会播放，目前发现只有从App才能将音乐暂停
2、截图标明的地方更希望只有调出播放界面这一种功能(类似于YouTube music 这种) 
3、应用内的手势返回有点问题，似乎除了播放界面会返回到上一个界面其余返回都是直接退出APP(也希望手势返回退出APP是连续两次，如果设计理念不同就算了吧)

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**
![20210529_171533.jpg](https://user-images.githubusercontent.com/65595091/120065214-bb078800-c0a2-11eb-821b-e9fa32cacfb5.jpg)

**环境：**
  -操作系统及版本：[例如：Android 10]
  -软件安装包及版本：[例如：1.0.0 arm64-v8a]

**其他内容**

**Comment by lyswhut** [comment]
1、由于注册了播放服务，所以划卡前需要停止播放才能停止APP
2、外面的播放控制栏目前先这样，以后再看情况改
3、此问题在v0.4.0起已修正
