### ISSUE TITLE
歌单“更多”键没法点

### ISSUE THREAD

**Issue by SurplusOK** [lyswhut/lx-music-mobile#157]
https://user-images.githubusercontent.com/69712074/194828109-c1c55149-6eb8-4691-85c2-4fd6818e13f0.mp4
我点击歌单后面的三个点就崩溃了，版本是0.14.3安卓版

**Comment by lyswhut** [comment]
看起来是这句报的错：
https://github.com/lyswhut/lx-music-mobile/blob/e7fec74abaf5d331855a1cc51260a1b13811b56e/src/screens/Home/List/components/MyList.js#L307

所有歌单的菜单都打不开吗？出问题的歌单是怎么收藏的？去设置-备份与恢复将列表导出来后将扩展名改为`.gz`解压看看？

**Comment by lyswhut** [comment]
这是由于PC端在某些情况下生成了意外的歌单元数据，这些意外的数据导致了移动端崩溃

**Comment by lyswhut** [comment]
已在v0.15.0修复
