### ISSUE TITLE
[Feature]: 请求增加dlna功能，能投放到wifi音箱上

### ISSUE THREAD

**Issue by 107295472** [lyswhut/lx-music-mobile#161]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

增加安卓上的投放到wifi音箱的功能

### 描述你想要的解决方案

看了下代码是c++，有点难

**Comment by weshion** [comment]
同意，很需要这个功能
