### ISSUE TITLE
添加【歌词悬浮窗】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#17]
**解决方案检查**

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

添加【歌词悬浮窗】功能，用户可以选择歌词颜色并调整字体大小。

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
已在v0.6.0添加桌面歌词
