### ISSUE TITLE
[Feature]: 希望能添加缓存歌单的功能

### ISSUE THREAD

**Issue by mycraftmw** [lyswhut/lx-music-mobile#171]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在软件的对音乐的缓存是需要点击播放音乐之后才会缓存，如果要实现对整个歌单的歌曲的缓存则需要每个都播放一遍。希望能提供一个功能去一次性的缓存整个歌单的歌曲。

### 描述你想要的解决方案

在歌单的`...`按钮中添加按钮`缓存歌单`，点击按钮就会开始依次缓存歌单中的所有歌曲，直到歌单中的全部歌曲被缓存或者是缓存大小达到设置中的上限。

**Comment by lyswhut** [comment]
缓存功能是由[播放模块](https://github.com/lyswhut/react-native-track-player)在播放歌曲时顺便缓存的，该模块没有提供不播放歌曲而直接缓存数据的API，
而且想要不播放歌曲的情况下缓存所有歌曲还不如直接添加下载功能，所以这个目前无法实现
