### ISSUE TITLE
[Bug]:  问 怎么取消下载irc格式

### ISSUE THREAD

**Issue by BrokenWings123** [lyswhut/lx-music-mobile#173]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

已经取消下载歌词， 只下载音乐 以及封面， 但是还会出现irc格式

### 实际行为

已经取消下载歌词， 只下载音乐 以及封面， 但是还会出现irc格式

### Lx Music 版本

1.22.3

### 操作系统版本

macbook arm 64

**Comment by lyswhut** [comment]
设置-下载设置-lrc歌词下载
这是移动端仓库，pc端的问题请去pc端项目。
