### ISSUE TITLE
添加【用户自建歌单】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#18]
**解决方案检查**

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

用户可以新建歌单并且命名，歌单里选择性保存歌曲并自定义排序。

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
用户自建歌单可以在添加、移动歌曲的弹窗内新建
