### ISSUE TITLE
[Bug]:  加载gradle 失败

### ISSUE THREAD

**Issue by jlianphoto** [lyswhut/lx-music-mobile#185]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

按照文档配置环境可以正常跑起项目

### 实际行为

已经按照文档install和react native 0.68 配置好相关环境，
但加载gradle的时候报错： /Users/jlian/Project/lx-music-mobile/android/keystore.properties (No such file or directory)

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/21987630/211739995-5eea7501-2c40-412f-af32-fbdec2425625.png">

### Lx Music 版本

v0.15.5

### 操作系统版本

android 11

**Comment by lhjgege** [comment]
虽然我不懂RN，但是这个不是bug吧，你难道不应该把他设置的签名文件给去除掉吗？这个是他本地设置签名文件路径。而且他没有上传到项目里面所以就没有这个文件路径咯。

**Comment by tohsaka888** [comment]
`README`有写怎么解决，仔细看呀
