### ISSUE TITLE
添加 能够获取的嵌入式音效插件，添加【音效】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#19]
**解决方案检查**

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

添加 能够获取的嵌入式音效插件，添加【音效】功能

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
目前不考虑添加音效功能
