### ISSUE TITLE
播放界面无法横屏

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#20]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

设计横屏的播放界面

**截图**

![Screenshot_2021-05-30-22-45-55-1984198395.png](https://user-images.githubusercontent.com/69227436/120108753-79d4ae00-c15e-11eb-9f1c-b24e113b7d27.png)

**环境：**
  -操作系统及版本：[例如：Android 10]
  -软件安装包及版本：[例如：1.0.0 arm64-v8a]

**其他内容**

**Comment by lyswhut** [comment]
v0.7.0起已添加横屏播放详情页
