### ISSUE TITLE
[Bug]: 电脑端版本 2.1.2 与 手机端版本 0.15.5 无法数据同步

### ISSUE THREAD

**Issue by xiaoqiangclub** [lyswhut/lx-music-mobile#207]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

电脑端版本 2.1.2 与 手机端版本 0.15.5 无法数据同步

### 实际行为

电脑端版本 2.1.2 与 手机端版本 0.15.5 无法数据同步

### Lx Music 版本

2.12

### 操作系统版本

MIUI14.0.3.0

**Comment by navie-cnima** [comment]
文档里好像写了。
此功能是实验性的，v2.0.0的同步功能不支持与移动端v1.0.0之前版本的使用，需等待后面的新版移动端，目前移动端v1的开发工作已在进行中，若仍然想要使用此功能可以下载[v1.22.3](https://github.com/lyswhut/lx-music-desktop/releases/tag/v1.22.3)绿色版用着先，后面同步在新版可以用了再用新版，到时候清理[数据目录](https://lxmusic.toside.cn/desktop/datapath)下的LxDatas重新自动迁移旧版数据即可
https://lxmusic.toside.cn/mobile/faq/sync
