### ISSUE TITLE
添加【流媒体播放】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#21]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

添加【流媒体播放】功能。通过局域网连接，DLNA技术，遥控TV或者PC等设备流媒体播放歌曲。

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
目前不计划添加流媒体功能
