### ISSUE TITLE
[Bug]: 点击通知栏控件，无法回到lx-music app界面

### ISSUE THREAD

**Issue by ameaninglessname** [lyswhut/lx-music-mobile#224]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望点击通知栏控件，可以像点击app图标一样，回到app界面

### 实际行为

通知栏收起，但是app没打开

### Lx Music 版本

1.0.3(57003) arm64-v8a

### 操作系统版本

Android 12 CrDroid 8.9

### 附加信息

![image](https://user-images.githubusercontent.com/20263103/229017880-be8fa8fd-404b-40f3-89ec-a0efe8a7f1f8.png)

**Comment by lyswhut** [comment]
尝试换个点击区域，在其他设备上测试是正常的
