### ISSUE TITLE
[Bug]: Arm eabi v7版本异常，找不到RSA_pkeyvctx_ctrl referenced by libreact-native-quick-crypto.so

### ISSUE THREAD

**Issue by ShiningDrops** [lyswhut/lx-music-mobile#229]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

点击播放

### 实际行为

所有音频都不能在线播放，提示找不到调用的函数

### Lx Music 版本

armeabi v7

### 操作系统版本

android 5

### 附加信息

Unexp

应用出bug了面，
息，请截图(并时上期才你进行?么操作)通过企鹏群或者Github反馈，现在应用可能会出现异常，看出现异常请尝试强制结束APP后重新启动!
Error
Fatal: Error Exception in HostFunction:
java.lang.UnsatisfiedLinkError
dlopen failed: cannot locate symbol“RSApkey_ctx_ctrl" referenced by"libreact-native-quick-crypto.so

**Comment by Resgining** [comment]
最低版本要求安卓6

**Comment by ShiningDrops** [comment]
多谢指点。老版本app支持安卓5，看来只能回退了。
建议修改下项目的配置，把支持的最低版本改一下，实现不支持的安卓版本就不能安装

**Comment by lyswhut** [comment]
v1.0.5已修复该问题
