### ISSUE TITLE
[Bug]: MIUI14后台杀死应用，音乐还会继续播放一段时间

### ISSUE THREAD

**Issue by HotRockit** [lyswhut/lx-music-mobile#231]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在后台杀死应用进程，音乐应该立即停止播放

### 实际行为

在MIUI14上后台杀死应用，音乐还会继续播放一段时间，在华为手机上没有问题

### Lx Music 版本

任何版本都有这个问题

### 操作系统版本

MIUI14对应Android13

**Comment by Resgining** [comment]
那应该是小米的问题
