### ISSUE TITLE
尝试自己编译打包出现 ，keystore.properties 文件找不到

### ISSUE THREAD

**Issue by supremew** [lyswhut/lx-music-mobile#24]
在 arch 上尝试自己编译打包时， 出来点问题：

1. 需要将 package.json 中的 如下内容

    "pack:android": "./gradlew assembleRelease"
修改为 
    "pack:android": "cd android && ./gradlew assembleRelease"

继续编译打包

```
yarn run pack:android
```

出现了如下错误,这就解决不了了。

* Where:
Build file '/home/archlinux/Build/lx-music-mobile/android/app/build.gradle' line: 176

* What went wrong:
A problem occurred evaluating project ':app'.
> /home/archlinux/Build/lx-music-mobile/android/keystore.properties (No such file or directory)

**Comment by lyswhut** [comment]
`keystore.properties`是APP签名配置文件，首先你需要生成自己的证书，
然后创建配置文件 `android\keystore.properties`文件，并根据你的证书信息在文件中写入以下内容：
```
storeFile=xxx
storePassword=xxx
keyAlias=xxx
keyPassword=xxx
```

**Comment by supremew** [comment]
能告诉一下这个证书怎么生成了， 很好奇！

**Comment by lyswhut** [comment]
自己百度 `react native 生成签名密钥`

**Comment by AleoJoker** [comment]
> 能告诉一下这个证书怎么生成了， 很好奇！

老哥，不看react-native官方文档的吗？

**Comment by a153884673** [comment]
到第四步吗，加载一遍gradle 时也要 先生成签名文件才行吗 C:\Users\Desktop\lx-mobile\lx-music-mobile\android\keystore.properties (系统找不到指定的文件。)

**Comment by a153884673** [comment]
到第四步吗，加载一遍gradle 时 也会报这个错 C:\Users\Desktop\lx-mobile\lx-music-mobile\android\keystore.properties (系统找不到指定的文件。) 也要 先生成签名文件才行吗
