### ISSUE TITLE
你用react native的话，相当于重写前端了，工作量挺大的

### ISSUE THREAD

**Issue by hugetiny** [lyswhut/lx-music-mobile#25]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

不用react好久了，记得RN以前也好多坑，也没有vue迁移react native的方案。你原来的前端代码是vue，用一些基于vue的跨平台的前端框架比较好。

**描述您考虑过的替代方案**
我用下来国内最好的框架是uni-app,国外最好的是Quasar
用响应式的代码写一套前端就够了，毕竟音乐app，调用原生功能的需求不多。

**其他内容**

**Comment by lyswhut** [comment]
这类应用原生还是必须的，不然很多功能实现不了，压缩、解压、读写文件，以后如果要实现桌面歌词、桌面挂件等，现在用rn的话底层可以使用exoplayer，想要操作原生也很方便，第一次用react与RN，正好熟悉下，react 有了hook是真的香

**Comment by hugetiny** [comment]
压缩、解压不清楚。读写文件都可以的。
当然顺便学RN的话，还是看你选择了。工程量很大啊。

**Comment by AleoJoker** [comment]
> 压缩、解压不清楚。读写文件都可以的。
> 当然顺便学RN的话，还是看你选择了。工程量很大啊。

这么说吧，uni-app我很早就试过了，用不了作者的接口，作者的接口对请求头的要求很高，有些头uni-app会自动加上，导致ip被接口服务器封掉

**Comment by AleoJoker** [comment]
> 压缩、解压不清楚。读写文件都可以的。
> 当然顺便学RN的话，还是看你选择了。工程量很大啊。

因为uni-app修改不了User-Agent，就用不了ts.tempmusic.tk的接口，哈哈

**Comment by YouWillBe** [comment]
flutter
