### ISSUE TITLE
[Feature]: 希望加入定时关闭 的的功能

### ISSUE THREAD

**Issue by GWU00099** [lyswhut/lx-music-mobile#258]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

添加定时关闭选项，跟酷狗音乐的功能差不多

### 描述你想要的解决方案

添加定时 10分钟 20分钟或自定义时间，定时结束后停止播放或退出软件，再加入播放完整首再停止按钮，

**Comment by 2046553272** [comment]
其实应该是有的
![Uploading Screenshot_2023-05-18-06-39-30-09_e8006ac6687f9360156c8c0dbce466ec.jpg…]()

**Comment by 2046553272** [comment]
![Screenshot_2023-05-18-06-39-30-09_e8006ac6687f936](https://github.com/lyswhut/lx-music-mobile/assets/70498814/b9c558a8-3c38-4073-9e7a-28578828c5ac)

**Comment by 2046553272** [comment]
不是有这个功能吗？
![Screenshot_2023-05-18-06-39-30-09_e8006ac6687f936](https://github.com/lyswhut/lx-music-mobile/assets/70498814/0b37a172-a127-45b3-876e-8ae0aaa8c1ae)

**Comment by GWU00099** [comment]
之前一直在设置里面翻，哈哈哈哈
