### ISSUE TITLE
默认接口为临时接口

### ISSUE THREAD

**Issue by HzRr** [lyswhut/lx-music-mobile#274]
手机版应用下载后，设置界面发现接口是临时接口而不是测试接口，会对刚开始使用的用户产生影响

**Comment by mcok** [comment]
是有影响，在搜段奥娟的《凡人》时，发现临时接口是不能播放的，测试接口正常播放

**Comment by Folltoshe** [comment]
为了提高使用门槛，软件内的默认设置不会以新手友好为目标。
