### ISSUE TITLE
[Feature]: 建议为桌面歌词增加描边或者字体阴影选项，纯色的桌面歌词在一些背景颜色上会看不清楚

### ISSUE THREAD

**Issue by ieayoio** [lyswhut/lx-music-mobile#276]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议为桌面歌词增加描边或者字体阴影选项，纯色的桌面歌词在一些背景颜色上会看不清楚，目前现有的歌词颜色普遍颜色偏浅或者太刺眼，我个人认为黑色效果最好，但是还是会出现一些情况下看不清的情况，下面是一些展示：

![bd3ee19d187594186e7e7e96dd7c068a](https://github.com/lyswhut/lx-music-mobile/assets/7099604/17710d2c-896a-4889-8203-e3b50c364212)

![79290ca89c6fa2cfe91c9073e2327181](https://github.com/lyswhut/lx-music-mobile/assets/7099604/ac50bbef-8ab2-49c9-9e85-9a86b1965c30)

![1b2318a05a88b7066ce2681eb7cdbe73](https://github.com/lyswhut/lx-music-mobile/assets/7099604/626292fa-f4a8-4db0-bf77-cc10530959bd)

### 描述你想要的解决方案

建议为桌面歌词增加描边或者字体阴影选项，可以有效的解决在不用的环境下歌词不清晰问题

### 描述你考虑过的替代方案

可暂时增加一些偏深色颜色的字体，很多情况下不会那么刺眼

**Comment by lyswhut** [comment]
已在v1.1.0进行了优化
