### ISSUE TITLE
[Bug]: 息屏状态无法输出歌词

### ISSUE THREAD

**Issue by banzhiz** [lyswhut/lx-music-mobile#277]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望息屏显示上实时显示当前播放歌曲歌词（搭配墨状态栏歌词和墨息，其他适配应用正常）

### 实际行为

会卡一句或者不显示，是不是锁屏后就不输出歌词了

### Lx Music 版本

1.0.6 arm64-v8a

### 操作系统版本

Android 13

**Comment by lyswhut** [comment]
为了节省电量，息屏会暂停歌词播放器，后面考虑在状态栏歌词版本添加一个开关控制是否息屏暂停歌词播放

**Comment by lyswhut** [comment]
已在v1.1.0的sl版本新增
