### ISSUE TITLE
能否支持4.4.4系统，现在的安装不了提示解包错误

### ISSUE THREAD

**Issue by bush688** [lyswhut/lx-music-mobile#28]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
不保证android 4.4的可用性，但你可以尝试安装`universal`那个包
