### ISSUE TITLE
[Feature]: 增添网页版web online version

### ISSUE THREAD

**Issue by chrisslatte** [lyswhut/lx-music-mobile#284]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

建议增加网页版，使得各类设备都快捷使用，各设备端无需多次开发，也能兼顾了iOS设备。
### 描述你想要的解决方案

增加可以使用浏览器访问的页面。

**Comment by dajiangjunok** [comment]
跨端构建的话   多一个web端确实是一个好的方式

**Comment by helloplhm-qwq** [comment]
需要考虑csrf问题，全部请求接口的话服务器压力太大，

**Comment by logic-coder** [comment]
同建议增加网页版，使得iOS用户也能有替代解决方案

**Comment by zhongwen-4** [comment]
> 同建议增加网页版，使得iOS用户也能有替代解决方案

都说了作者没钱搞服务器了，你还想怎样，要iOS你拿个iOS模板编译一下不就好了

**Comment by chrisslatte** [comment]
> 同建议增加网页版，使得iOS用户也能有替代解决方案

我原本的意思是说，网页版跨设备使用更便捷且无需针对各个操作系统额外开发，并非专门为了iOS设备开发。

**Comment by zhongwen-4** [comment]
> > 同建议增加网页版，使得iOS用户也能有替代解决方案
> 
> 我原本的意思是说，网页版跨设备使用更便捷且无需针对各个操作系统额外开发，并非专门为了iOS设备开发。

首先，网页版需要防ddos，其次，网页版有一堆奇奇怪怪的问题，最后，作者没钱🤔

**Comment by lyswhut** [comment]
即使有网页版也只是提供源码，需要自己用服务器部署

**Comment by disburden** [comment]
> 即使有网页版也只是提供源码，需要自己用服务器部署

那到底是有还是没有啊?自己服务器部署没问题,现在能来github的基本上都有nas,同步服务器很多人不也是自己部署的.
强烈希望解决ios端问题,web是个办法
