### ISSUE TITLE
[Feature]: 歌曲不播放时,  手动滚动歌词取消自动滚动到对应播放位置。

### ISSUE THREAD

**Issue by licheng1013** [lyswhut/lx-music-mobile#298]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

目前歌曲不播放时，滚动歌词后，停止滚动后会在一定时候滚动回播放位置。

### 描述你想要的解决方案

希望支持，歌曲不播放时滚动歌词，当停止后不在滚回到播放位置。

**Comment by lyswhut** [comment]
已在v1.1.0优化
