### ISSUE TITLE
[功能问题]启用顺序播放，当整个列表播放完之后，播放控件仍处于 播放状态，应当重置为暂停状态。

### ISSUE THREAD

**Issue by richild999** [lyswhut/lx-music-mobile#300]

**Comment by richild999** [comment]
> 

![Screenshot_2023-09-02-19-01-25-912_cn.toside.music.mobile.jpg](https://github.com/lyswhut/lx-music-mobile/assets/53998175/947b33e5-5139-4390-a7d8-02d979f4f0c6)

**Comment by lyswhut** [comment]
已在v1.1.0修复
