### ISSUE TITLE
[Feature]: 在播放详情页增加分享按钮

### ISSUE THREAD

**Issue by cheakin** [lyswhut/lx-music-mobile#308]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

现在我要分享一首歌，是先到我的收藏里搜索这首歌，然后点下拉之后分享。
无法在正在播放的详情页中分享

### 描述你想要的解决方案

在正在播放的详情页中增加分享按钮

**Comment by zhongwen-4** [comment]
这不是有分享吗![Uploading Screenshot_2023-09-12-10-00-29-842_com.folltoshe.lxmusic.plus.mobile.jpg…]()

**Comment by zhongwen-4** [comment]
这不是有分享按钮吗
![Uploading Screenshot_2023-09-12-10-00-29-842_com.folltoshe.lxmusic.plus.mobile.jpg…]()

**Comment by zhongwen-4** [comment]
![Screenshot_2023-09-12-10-00-29-842_com folltoshe lxmusic plus mobile](https://github.com/lyswhut/lx-music-mobile/assets/114509415/8cb0d41e-3644-4b32-b678-69c6ba5581e2)

**Comment by zhongwen-4** [comment]
这不是有分享按钮吗
![Screenshot_2023-09-12-10-00-29-842_com folltoshe lxmusic plus mobile](https://github.com/lyswhut/lx-music-mobile/assets/114509415/0dd90121-37ab-42a1-908b-a657ea92e7c9)

**Comment by cheakin** [comment]
> 这不是有分享按钮吗 ![Screenshot_2023-09-12-10-00-29-842_com folltoshe lxmusic plus mobile](https://user-images.githubusercontent.com/114509415/267188892-0dd90121-37ab-42a1-908b-a657ea92e7c9.jpg)

我的意思在播放详情页里增加这个按钮。
原因是因为我听一首名字奇奇怪怪的歌的时候，我想要分享，但我在搜索时我压根不会打歌名。另外我在有几百歌的歌单中想找到我正在听的歌并不容易。

**Comment by zhongwen-4** [comment]
> > 这不是有分享按钮吗 ![Screenshot_2023-09-12-10-00-29-842_com folltoshe lxmusic plus mobile](https://user-images.githubusercontent.com/114509415/267188892-0dd90121-37ab-42a1-908b-a657ea92e7c9.jpg)
> 
> 我的意思在播放详情页里增加这个按钮。 原因是因为我听一首名字奇奇怪怪的歌的时候，我想要分享，但我在搜索时我压根不会打歌名。另外我在有几百歌的歌单中想找到我正在听的歌并不容易。

长按左下角图片有定位功能

**Comment by cheakin** [comment]
> > > 这不是有分享按钮吗 ![Screenshot_2023-09-12-10-00-29-842_com folltoshe lxmusic plus mobile](https://user-images.githubusercontent.com/114509415/267188892-0dd90121-37ab-42a1-908b-a657ea92e7c9.jpg)
> > 
> > 
> > 我的意思在播放详情页里增加这个按钮。 原因是因为我听一首名字奇奇怪怪的歌的时候，我想要分享，但我在搜索时我压根不会打歌名。另外我在有几百歌的歌单中想找到我正在听的歌并不容易。
> 
> 长按左下角图片有定位功能

6，我不知道有这个功能，抱歉。那我将这个问题关闭了吧！
