### ISSUE TITLE
怎么导入电脑端导出的歌单

### ISSUE THREAD

**Issue by rickiey** [lyswhut/lx-music-mobile#309]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

没法导入电脑端导出的歌单，看不到文件

### 描述你想要的解决方案

导入文件

**Comment by rickiey** [comment]
导入列表时同一个目录下两个文件为啥只能看到一个

**Comment by rickiey** [comment]
好吧，改个后缀就好了，不怎么到怎么吧后缀搞没了

**Comment by rickiey** [comment]
导入失败

**Comment by zhongwen-4** [comment]
直接同步不就行了，要什么导出歌单😓

**Comment by lyswhut** [comment]
> 想把列表同步到另一个手机上。 用导出列表后是没有后缀的，看了你这个回复之后才加了后缀导入新机。

你是使用右上角存储卡按钮的 `content://` 路径打开的文件导出的吗？

**Comment by lyswhut** [comment]
> 是的！

可以试试最新版是否已修复没有后缀的问题

**Comment by lyswhut** [comment]
> 不会下这个链接里的测试版

点最新的构建，在登录GitHub账号时可以点页面下面的对应版本包下载，下载后解压出来就是安装包
