### ISSUE TITLE
[Bug]: 低版本安卓无自动暗黑模式

### ISSUE THREAD

**Issue by orency** [lyswhut/lx-music-mobile#317]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

可以跟随系统暗黑模式设定,包括系统自带(安卓10及以上),通过第三方app(安卓4.1及以上)

### 实际行为

安卓10以下跟随系统亮暗模式切换主题选项被隐藏(应该是作者故意为之?)
导致无法自动切换暗黑模式

### Lx Music 版本

1.1.0 arm64

### 操作系统版本

android 10 以下

### 附加信息

尽管安卓10以下系统未提供开关切换暗黑模式,但可以通过一些第三方app做到.如[深色模式切换](https://github.com/dadaewq/Dark-Mode-Switch)
因为只是修改一个系统prop值,而这个值实际在**安卓4.1**就已经存在.所以理论上**安卓4.1**以上都是可以通过读取这个值跟随系统暗黑模式设定的
最低在miui安卓7上实测通过第三方app切换方式无需root和常驻后台就可以使有此功能的绝大部分app正常自动跟随切换(除了极少数人为限制的),与安卓10及以上系统自带的相比几乎没有差别
所以lx不应该也没必要限定安卓10以下无法使用此功能

**Comment by lyswhut** [comment]
下个版本可以取消屏蔽，对安卓不了解，之前看文档说是10才支持就做了处理

**Comment by orency** [comment]
> 下个版本可以取消屏蔽，对安卓不了解，之前看文档说是10才支持就做了处理

实际是安卓10原生系统才正式提供了磁贴切换方式,但安卓9在开发者模式中就可以切换的.甚至有些第三方定制比如魅族在安卓7就提供了切换开关.
而这个切换的系统属性在安卓4.1就已经存在了,属于是一个早就安排上却很晚原生系统才有gui的功能.
这类功能实在太多,比如隐私权限,分身等等,然后定制厂商在其中掘宝成卖点.等到原生系统正式推出gui的时候,一堆无良媒体反倒呱呱谷歌抄袭了某某早就有的功能😅

**Comment by lyswhut** [comment]
已在v1.2.0开放该选项
