### ISSUE TITLE
重启软件 会有小概率无法继续听上次未结束的歌

### ISSUE THREAD

**Issue by qw1324** [lyswhut/lx-music-mobile#32]
![Screenshot_20210728-202101](https://user-images.githubusercontent.com/49418651/127412791-1b96e1b7-1f56-4527-b488-ec9950d5ff66.jpg)
崩溃日记

**Comment by lyswhut** [comment]
你说下你上次的操作步骤吗？

**Comment by qw1324** [comment]
https://user-images.githubusercontent.com/49418651/127413482-74180caf-5c28-4230-a9ad-c8fb41e00cc0.mp4

这个是我上次的操作步骤 导致的会小概率获取不到上次的歌曲

对了 我这边在提一个问题 点击那个停止按钮的时候 会有小概率无法结束应用 步骤都是一样

**Comment by lyswhut** [comment]
你默认列表里的歌曲还在吗？还剩181首？

若在播放详情界面点停止按钮则只是退出播放详情界面，点完停止再划卡清理即可

**Comment by qw1324** [comment]
还在的 只是恢复上次听的歌曲会有小概率无法获取

**Comment by lyswhut** [comment]
这是想要恢复播放第182首歌，但是你列表只有181首，导致恢复失败

**Comment by qw1324** [comment]
我会尽量想办法再重现一下(bushi

这个问题我也没遇到过几次 所以也不知道具体原因

**Comment by lyswhut** [comment]
你上次是不是在结束软件前的两秒内删过列表的歌曲？
刚才review了一下代码，找到了一个能重现这个错误的操作：播放最后一首歌，删掉那首歌马上结束掉应用，下次打开就会出现这个问题，这是由于播放信息延迟了2秒存储导致的
至于前面你遇到的问题是不是这样导致的我就不清楚了

**Comment by qw1324** [comment]
好像没有删过

lyswhut ***@***.***> 于 2021年7月28日周三 下午9:03写道：

**Comment by qw1324** [comment]
有有有 我记得我有清理过列表来着

凌天 ***@***.***> 于 2021年7月28日周三 下午9:04写道：

**Comment by lyswhut** [comment]
下版本会修复这个问题，应该是这个问题导致的，
还有一种重现方法是：播放列表的最后一首歌，然后删掉正在播放的这首歌后马上按返回键或home键将程序切到后台，**在不将软件切到前台的情况下**，你随便播放、切换歌曲（用通知栏、耳机切换）都可以正常使用，最后再结束掉程序也会出现这个问题

**Comment by qw1324** [comment]
我试试第二种重现法

lyswhut ***@***.***> 于 2021年7月28日周三 下午9:19写道：

**Comment by qw1324** [comment]
出现了

凌天 ***@***.***> 于 2021年7月28日周三 下午9:20写道：

**Comment by qw1324** [comment]
https://user-images.githubusercontent.com/49418651/127416878-c0d65dce-5814-441e-88d2-4252d3cb51f2.mp4

这个是刚刚第二种重现方法的视频
