### ISSUE TITLE
[Feature]: ios端讨论专贴

### ISSUE THREAD

**Issue by disburden** [lyswhut/lx-music-mobile#325]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

相信有很大一部分人需要有个ios端的版本,我搜了一下,类似的帖子和回复都不少.但都是各种建议方案,包括自己编译,web方式等等,却没有一个真正可提供下载测试的版本.估计有很多人都在默默的尝试的,最终都是遇到各种各样的问题放弃了.

开这个帖子的目的是想让正在尝试的朋友们把遇到的问题统一发在这个帖子里,发挥网络的力量,可能你遇到的问题别人已经解决了,或者别人遇到的问题你已经遇到过了,之前的零零散散的分散在不同的帖子里,找起来不方便,以后统一发在这里,大家互通一下有无,希望早日有牛人整出一个可用的版本,造福一方像我这样的伸手党.

祝大家早日在苹果手机上看到落雪!

### 描述你想要的解决方案

ios端app

### 描述你考虑过的替代方案

web方式

**Comment by disburden** [comment]
有一点我觉的挺奇怪的,要说苹果那头非常龟毛,问题一堆还情有可原.但是我简单瞄了一下项目源码,好像是用typescript写的,照理说应该发布个web版本很容易啊,为啥web版的也都没见到?

**Comment by zhongwen-4** [comment]
> 有一点我觉的挺奇怪的,要说苹果那头非常龟毛,问题一堆还情有可原.但是我简单瞄了一下项目源码,好像是用typescript写的,照理说应该发布个web版本很容易啊,为啥web版的也都没见到?

网页版会被ddos，就算你网站防住了，那接口呢

**Comment by zhongwen-4** [comment]
> 有一点我觉的挺奇怪的,要说苹果那头非常龟毛,问题一堆还情有可原.但是我简单瞄了一下项目源码,好像是用typescript写的,照理说应该发布个web版本很容易啊,为啥web版的也都没见到?

而且网页版的开发会导致用户量暴增，到时候服务器撑不住了你来解决服务器的问题?而且用户量暴增就可能会被那些大厂盯上，到时候那些大厂的律师函反正不是发到你手里哦

**Comment by disburden** [comment]
> > 有一点我觉的挺奇怪的,要说苹果那头非常龟毛,问题一堆还情有可原.但是我简单瞄了一下项目源码,好像是用typescript写的,照理说应该发布个web版本很容易啊,为啥web版的也都没见到?
> 
> 而且网页版的开发会导致用户量暴增，到时候服务器撑不住了你来解决服务器的问题?而且用户量暴增就可能会被那些大厂盯上，到时候那些大厂的律师函反正不是发到你手里哦

开发和部署是两回事
我的意思是开发(或者编译)好一个网页版,让用户下载后自己去部署,官方只发布源码,用户自己部署.
我之前有提到过,现在有github账号的估计大多数都有nas,完全可以部署在自己的nas上
就像官方出的收藏夹同步服务器,可以自己部署同步服务器.

**Comment by zhongwen-4** [comment]
> > > 有一点我觉的挺奇怪的,要说苹果那头非常龟毛,问题一堆还情有可原.但是我简单瞄了一下项目源码,好像是用typescript写的,照理说应该发布个web版本很容易啊,为啥web版的也都没见到?
> > 
> > 
> > 而且网页版的开发会导致用户量暴增，到时候服务器撑不住了你来解决服务器的问题?而且用户量暴增就可能会被那些大厂盯上，到时候那些大厂的律师函反正不是发到你手里哦
> 
> 开发和部署是两回事 我的意思是开发(或者编译)好一个网页版,让用户下载后自己去部署,官方只发布源码,用户自己部署. 我之前有提到过,现在有github账号的估计大多数都有nas,完全可以部署在自己的nas上 就像官方出的收藏夹同步服务器,可以自己部署同步服务器.

有没有一种可能，这个软件虽然开源了，但是没完全开源，虽然99.9%的源码全在这了，但是还有0.1%的东西不能开源

**Comment by disburden** [comment]
@zhongwen-4 不懂哦
不过应该不至于,这个项目有774个fork,说明其他人都能编译过,就算有那么0.1%不开源,应该也是以某种包或者动态链接库一类的存在,不会影响使用.

**Comment by zhongwen-4** [comment]
> @zhongwen-4 不懂哦 不过应该不至于,这个项目有774个fork,说明其他人都能编译过,就算有那么0.1%不开源,应该也是以某种包或者动态链接库一类的存在,不会影响使用.

fork貌似不代表一定会编译吧，我记得那缺失的一部分好像是歌词部分的一个块还是什么东西

**Comment by disburden** [comment]
> > @zhongwen-4 不懂哦 不过应该不至于,这个项目有774个fork,说明其他人都能编译过,就算有那么0.1%不开源,应该也是以某种包或者动态链接库一类的存在,不会影响使用.
> 
> fork貌似不代表一定会编译吧，我记得那缺失的一部分好像是歌词部分的一个块还是什么东西

fork不代表会编译,但pr可以,这个项目现在还有两个pr请求,正常能发起pr请求的应该都是自己编译过确认没问题的.

**Comment by disburden** [comment]
> 我自己有开发[播放器](https://github.com/lovegaoshi/azusa-player-mobile)，RN技术栈，有可运行的ipa文件，最近也略有涉及整合平台这块儿 落雪的问题是用了安卓的crypto库而不是用js的，你直接套ios不行；相比之下MusicFree用的是js，我的播放器可以稍作修改就直接导入MusicFree的规则然后解析播放。 MusicFree由于也有私有安卓库所以他不做大改也跑不起来ipa。 另外苹果AVPlayer的播放支持不如安卓exoplayer广，偶尔会有问题。b站播放就时灵时不灵 如果有能力的朋友能port洛雪的网站解析，可以试试

哦,那我明白了,为什么那么多牛人,到现在都没有可用的ipa放出来
估计@zhongwen-4 说的0.1%就是这个
不知道编译成web会不会受到crypto库的影响

**Comment by lovegaoshi** [comment]
Lx没有闭源的代码，缺的是ios开发把安卓的库移植
lx桌面是electron，内部技术栈是node，想做成web要把前后端分开，比移植几个安卓库工程量大多了

**Comment by lovegaoshi** [comment]
可以啊，musicfree就是这个思路，他甚至做成了插件
我不知道listen1用的什么，但是他们好像有解析问题
musicfree解析没问题，我直接导入到我app里，但是没人维护这个
lx 桌面版用node专有的needle http请求库，RN用的安卓私有的加密crypto库，不改没法直接拿到ios上
问题的关键还是人人都是伸手党

**Comment by disburden** [comment]
@lovegaoshi 那你能教我怎么调用这个api吗?比如输入"花妖",应该能返回各个平台的播放地址,我用了好多年的flutter,水平一般,但是找个别人做好的播放器,把url放进去播放这个我应该是会,到时候ios,android,linux,windows,mac,web应该都能用.
另外如果真这么做了,我要怎么和api提供者把这个事说清楚?

**Comment by lovegaoshi** [comment]
你想直接拿落雪放进flutter是不可能的，js跟dart不一样
放进已有的RN项目，参考我导入musicfree：https://github.com/lovegaoshi/azusa-player-mobile/pull/157/files#diff-b15f33f85daefb1d2c3a0092046f8369d35e9a1211a1c382d55652a5e5c14fe9

另外的方法就是自建一个node的服务器
首先搭建一个解析的API服务器，比如这个内建的yt-dlp
https://github.com/lovegaoshi/yozora
搜索的时候请求指向这个服务器
你直接submodule lx桌面版然后用express建好API endpoint就行了

**Comment by lovegaoshi** [comment]
apache 2.0 不能用落雪的名字 其他的随便用

**Comment by disburden** [comment]
我看错了,我还以musicfree是把服务器端搜索功能做成了一个插件,原来他说的是支持插件的功能:(

**Comment by lovegaoshi** [comment]
朋友你得自己submodule 落雪桌面版然后搭express…
现成的musicfree能直接import进任何RN播放器啊，不然你试试我的
https://github.com/lovegaoshi/azusa-player-mobile/releases/download/v2.10.4/APM.ipa
sideload IPA －设置－开发者选项－plugins－musicfree－打勾
回主界面－右划－按左上角－musicfree－搜索

**Comment by disburden** [comment]
RN都没接触过
你发给我的那个ipa可以直接装到苹果手机里使用吗?

**Comment by lovegaoshi** [comment]
朋友你如果不会侧载ipa的话就不用考虑了- -
苹果用户买个会员不好吗，支持国产

**Comment by disburden** [comment]
买会员无所谓,我同时用华为和苹果两个手机,买了会员也无法保证体验一致.
最主要的一个问题是现在音乐版权这么分散,你想要听到你想要听的歌曲,不得装遍市面上所有主流音乐平台的播放器?
而且就算装了你还不知道版权在哪个平台,还得一个个平台搜一遍...
这不正是落雪,linsten1,musicfree他们要解决的问题吗

**Comment by disburden** [comment]
还有歌单同步的问题

**Comment by disburden** [comment]
![微信图片_20231011022338](https://github.com/lyswhut/lx-music-mobile/assets/1391188/0aeb65ad-76d9-4f12-991d-6da2acc8dcca)
你发的ipa我装了,好像能用,晚了,睡觉去,明天再试看看

**Comment by disburden** [comment]
@lovegaoshi 你现在只有一个搜索b站的插件可以用是吗?有落雪搜索的插件吗?

**Comment by disburden** [comment]
我没想把整个落雪播放器搬到ios
我是想希望有人把落雪搜索的那部分功能(应该就是你说的解析库)单独做成node项目
然后你不是发了你做ipa,我看了里没有落雪搜索的那个功能
插件如果一定是在本地解析那应该是没戏了
我想插件应该也可以是远程解析的吧,所以问问有没有落雪搜索的插件

**Comment by lovegaoshi** [comment]
- -之前不是说过了么 submodule lx桌面版搭一个node啊 想伸手就等

**Comment by disburden** [comment]
主要是不会:(
哎....

**Comment by disburden** [comment]
大致了解了,先这样

**Comment by anand-lyn** [comment]
24年，有人来捞一下吗

**Comment by liuqingdada** [comment]
最近换了iPhone，确实很痛苦

**Comment by Nadroid** [comment]
看到一个大佬写的flutter版本落雪，目前就差音乐问题未解决，感兴趣的大佬可以一起了解一下https://github.com/airshu/lx_music_flutter

**Comment by liuqingdada** [comment]
> 看到一个大佬写的flutter版本落雪，完成度比较高，目前就差音源问题未解决，感兴趣的大佬可以一起了解一下https://github.com/airshu/lx_music_flutter

这个太酷了

**Comment by FelixForever** [comment]
> @zhongwen-4 不懂哦 不过应该不至于,这个项目有774个fork,说明其他人都能编译过,就算有那么0.1%不开源,应该也是以某种包或者动态链接库一类的存在,不会影响使用.

有没有可能像我这种，就是fork一个到自己仓库备着的～
