### ISSUE TITLE
希望添加鸿蒙系统版本，麒麟9000处理器装不上

### ISSUE THREAD

**Issue by arno773877440** [lyswhut/lx-music-mobile#34]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

**描述您考虑过的替代方案**

**其他内容**

**Comment by arno773877440** [comment]
希望能够适配更多手机，望采纳

**Comment by lyswhut** [comment]
鸿蒙的话我看有人也可以用，你这边为啥不行我也不知道啥原因，尝试那个通用版的安装包，不行的话我也没办法了

**Comment by arno773877440** [comment]
谢谢，我尝试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月8日(周日) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lyswhut/lx-music-mobile] 希望添加鸿蒙系统版本，麒麟9000处理器装不上 (#34)




 
鸿蒙的话我看有人也可以用，你这边为啥不行我也不知道啥原因，尝试那个通用版的安装包，不行的话我也没办法了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangbyong** [comment]
可以用

**Comment by arno773877440** [comment]
> 可以用

谢谢， 我安装通用版安装上了
