### ISSUE TITLE
桌面歌词在没有播放时仍然显示灰色栏[Bug]: 

### ISSUE THREAD

**Issue by zjqf2021** [lyswhut/lx-music-mobile#364]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在不播放的情况下，桌面歌词灰色栏不需要显示（桌面歌词未设置为固定）

### 实际行为

当没有播放时，或者处于后台时，桌面歌词仍然显示灰色栏

### Lx Music 版本

1.2.0

### 操作系统版本

emui10

### 附加信息

![Screenshot_20231201_164627_com huawei android launcher](https://github.com/lyswhut/lx-music-mobile/assets/96340124/2afc7437-5132-46a8-a72d-cef8d4c35498)

**Comment by zjqf2021** [comment]
> 锁定歌词

不不，在不锁定的情况下 ，希望播放的时候显示灰色栏，不播放的时候灰色栏不显示

**Comment by LGXHTM** [comment]
你这个要求不好处理吧，qq/酷狗等也是同样的情况啊，那个灰色栏就是歌词的背景栏，只要你开启程序（开启了桌面歌词）就会显示的，希望播放的时候显示灰色栏，不播放的时候灰色栏不显示，这不就是希望播放的时候显示歌词，暂停播放的时候不显示歌词吗，而且这种风格并不适应每一个人。我的建议是可以把歌词的最大行数先改成5等比较大的，然后把灰色栏拉到手机最上面，再把最大行数改成1，这样灰色栏在顶部占的空间很小，不太能影响你使用其他软件或者功能@zjqf2021

**Comment by LGXHTM** [comment]
当然，你还可以选择支持状态栏功能的：
https://github.com/lyswhut/lx-music-mobile/actions/workflows/statusbar-lyric.yml

**Comment by zjqf2021** [comment]
> 你这个要求不好处理吧，qq/酷狗等也是同样的情况啊，那个灰色栏就是歌词的背景栏，只要你开启程序（开启了桌面歌词）就会显示的，希望播放的时候显示灰色栏，不播放的时候灰色栏不显示，这不就是希望播放的时候显示歌词，暂停播放的时候不显示歌词吗，而且这种风格并不适应每一个人。我的建议是可以把歌词的最大行数先改成5等比较大的，然后把灰色栏拉到手机最上面，再把最大行数改成1，这样灰色栏在顶部占的空间很小，不太能影响你使用其他软件或者功能@zjqf2021

可以加个判断：
 - playing：lycBar.style.visiable=true。
 -!playing：lycBar.style.visiable=false。

> 我的建议是可以把歌词的最大行数先改成5等比较大的
其实，这个只算是我个人的一个喜好吧，谢谢你的建议
