### ISSUE TITLE
未知错误 (我觉得是桌面歌词问题)

### ISSUE THREAD

**Issue by qw1324** [lyswhut/lx-music-mobile#37]
![Screenshot_20210808-150016__01](https://user-images.githubusercontent.com/49418651/128642922-4f51b4d6-7ff1-4327-85b0-2f1727f6a5cc.jpg)

不知道这个是什么问题

怎么触发的 我就不知道了

**Comment by lyswhut** [comment]
已在v0.6.2中修复
