### ISSUE TITLE
部分歌曲歌词不显示

### ISSUE THREAD

**Issue by Amrita4277** [lyswhut/lx-music-mobile#370]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

![Screenshot_20231210_140410_cn toside music mobilf](https://github.com/lyswhut/lx-music-mobile/assets/99092909/aa1b6aba-e4cf-42eb-b558-645a291ce8e2)

有些日文歌wy有歌词，但是lx上wy搜却无法正常显示

### Lx Music 版本

1.2.0-beta.8

### 操作系统版本

鸿蒙3.0

**Comment by Bleauuuu** [comment]
> 下次反馈此类问题请附上歌曲名文本
> 清理歌词缓存再播放看看，你截图里的这首歌的歌词在官方平台就是有问题的，歌词的时间格式是不对的：
> ![image](https://github.com/lyswhut/lx-music-mobile/assets/20365169/5abcb0da-6d36-4098-a2ff-f12a279ba257)
> 
> 正常的格式是 `xx:xx.xx`，只有前三句格式正确，后面的那些本来应该是`.`但是变成了`:`，时间标签匹配失败的歌词将会被丢弃
> 

感谢回复！缓存清理了还是无法解决。
ナツノセ这个歌手有好几首都是：
解氷
![Screenshot_20231211_153903_cn.toside.music.mobile.jpg](https://github.com/lyswhut/lx-music-mobile/assets/99092909/38d33dda-f0a4-4b7e-9037-6b3c57291ad0)
アイス
![Screenshot_20231211_153911_cn.toside.music.mobile.jpg](https://github.com/lyswhut/lx-music-mobile/assets/99092909/39c9d610-5fd2-4b66-94c7-f51005b15636)
アネモネと炭酸水
![Screenshot_20231211_154552_cn.toside.music.mobile.jpg](https://github.com/lyswhut/lx-music-mobile/assets/99092909/57df52a9-a785-4045-90e8-32e3dbf5913d)

请问还有什么解决方法吗

**Comment by lyswhut** [comment]
目前暂无代替解决方案，软件内没有手动换歌词的功能，可以去官方客户端看看是否正常？若官方平台也不正常可以给他们反馈，他们处理后清理歌词缓存重新再试即可

**Comment by Bleauuuu** [comment]
> 目前暂无代替解决方案，软件内没有手动换歌词的功能，可以去官方客户端看看是否正常？若官方平台也不正常可以给他们反馈，他们处理后清理歌词缓存重新再试即可

呃呃 官方都是正常显示的 这种情况也可以反馈吗（？）

**Comment by lyswhut** [comment]
官方没问题的那就不用向他们反馈，只有这种日语歌会出现这种情况吗？中文、英文歌曲会不会出现这个情况呢？

**Comment by Bleauuuu** [comment]
> 官方没问题的那就不用向他们反馈，只有这种日语歌会出现这种情况吗？中文、英文歌曲会不会出现这个情况呢？
> 

目前只遇到日文歌有个问题 中文和英文歌我也听了不少但没遇到过这种情况

**Comment by lyswhut** [comment]
下个版本会对这个源的歌词做修复处理

**Comment by Amrita4277** [comment]
> 下个版本会对这个源的歌词做修复处理

感谢！！

**Comment by Amrita4277** [comment]
> 下个版本会对这个源的歌词做修复处理

对了，还有个这种情况但目前只发现这首歌有
![Screenshot_20231212_193946_cn.toside.music.mobile.jpg](https://github.com/lyswhut/lx-music-mobile/assets/99092909/2bf90f76-2884-4a9d-8221-1dee43b71930)

![Screenshot_20231212_193951_com.netease.cloudmusic.jpg](https://github.com/lyswhut/lx-music-mobile/assets/99092909/e9f71bb3-9811-405a-93bb-970e4ec8faf1)

**Comment by lyswhut** [comment]
仍然是时间标签的问题，这种头部标签时间不对的情况不管了

**Comment by lyswhut** [comment]
安装 v1.2.0-beta.10 清理歌词缓存试试

**Comment by Amrita4277** [comment]
> 安装 v1.2.0-beta.10 清理歌词缓存试试

问题解决啦！大佬辛苦了！
