### ISSUE TITLE
[Bug]: 自1.2.0-beta8版本开始歌曲存在重复缓存现象

### ISSUE THREAD

**Issue by HashLiver** [lyswhut/lx-music-mobile#373]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

播放一次的歌曲的理应无需缓存，并可在断网情况下播放。

### 实际行为

通过断网发现：
* 切换歌曲存在重复缓存现象，播放过一次的歌曲在断网情况下无法播放；
* 拖动进度条卡顿竟然也是因为重复缓存，在**歌曲播放时**关闭移动数据或WiFi时再往前拖动进度条会显示“缓存中”然后“换源失败”而无法播放。

导致使用移动数据时拖动进度条和切歌会消耗大量流量！

现已回退至1.20-beta7，这是最后正常缓存的版本，而且进度条拖动非常流畅 :)

### Lx Music 版本

1.2.0-beta10

### 最后正常的版本

1.2.0-beta7

### 操作系统版本

Android 13

**Comment by lyswhut** [comment]
是的，beta.8更新播放模块时意外把缓存去掉了，尝试beta.11是否已修复
