### ISSUE TITLE
[Bug]: 车机或平板模式下beta11播放页面最左侧的三个按键无法点击

### ISSUE THREAD

**Issue by oozzbb** [lyswhut/lx-music-mobile#376]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

车机或平板模式下beta11播放页面最左侧的三个按键无法点击，beta7之后的版本都有这个问题
![无标题](https://github.com/lyswhut/lx-music-mobile/assets/5475510/53b40c92-b4e9-4d41-b1e1-b410bfeb9d16)

### 实际行为

车机或平板模式下beta11播放页面最左侧的三个按键无法点击

### Lx Music 版本

beta11

### 操作系统版本

android

**Comment by zxc205** [comment]
beta版怎么下？

**Comment by cxg12** [comment]
> beta版怎么下？



> 同问，bata版在哪下载

[https://github.com/lyswhut/lx-music-mobile/actions](url)

**Comment by lyswhut** [comment]
看看 1.2.0-beta.12 是否已修复
