### ISSUE TITLE
[Bug]: 歌曲播放到一分钟左右的时候会停顿几秒

### ISSUE THREAD

**Issue by alyssaivan** [lyswhut/lx-music-mobile#377]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望流畅完整的播完一整首歌曲，ps：是tx源的歌曲

### 实际行为

歌曲播放到一分钟左右的时候会停顿几秒，之后又会继续播放

### Lx Music 版本

1.2.0-beta.11

### 最后正常的版本

1.2.0-beta.7

### 操作系统版本

安卓13

**Comment by fengshgx** [comment]
请问一下bata版在哪下载

**Comment by yaoyak** [comment]
> 请问一下bata版在哪下载

actions

**Comment by lyswhut** [comment]
看 https://github.com/lyswhut/lx-music-mobile/issues/393
