### ISSUE TITLE
[Bug]: 本地歌曲flac格式解析封面异常导致界面卡死

### ISSUE THREAD

**Issue by zjqf2021** [lyswhut/lx-music-mobile#378]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

可以播放无损音质歌曲flac格式

### 实际行为

添加本地歌曲为flac格式，在播放时界面卡死，声音正常，歌曲切换下一首程序报错，mp3格式播放正常
![Screenshot_20231216_021114_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/96340124/596573f0-0db8-4c7d-88d6-dd14303c6da0)
![Screenshot_20231216_021609_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/96340124/009e0493-6236-4373-931d-2033dcd37362)
![Screenshot_20231216_020824_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/96340124/bc93a84b-219e-4b9d-9cf6-adf2988c26bb)

### Lx Music 版本

1.2.0 beta12

### 操作系统版本

emui10 Android10

**Comment by zjqf2021** [comment]
https://github.com/lyswhut/lx-music-mobile/assets/96340124/70855a3b-897e-4249-b756-5bf465fb0d75

这个是播放flac时界面卡死的现象

**Comment by zjqf2021** [comment]
原因找到了：
1. 解析“个别”flac封面异常导致点击播放栏无反应，且播放栏封面位置显示空白、播放界面卡死；
2. 编辑标签，增加封面图片后恢复正常。
3. 解析flac歌曲时出现2种情况：
    - 可以正常解析歌名，专辑等，但无法解析封面。
    - 可以解析封面，但解析歌名，专辑名等错误为“kuwo”。
    - 
[Uploading 音频.zip…]()

**Comment by lyswhut** [comment]
音频样本似乎没有上传成功？

**Comment by zjqf2021** [comment]
> 音频样本似乎没有上传成功

**Comment by zjqf2021** [comment]
> 音频样本似乎没有上传成功？

我用蓝奏浏览器分享了[音频], 下载链接:https://wwp.lanzoup.com/i9GC71i489wd  , 密码是2jdf

**Comment by lyswhut** [comment]
> 可以正常解析歌名，专辑等，但无法解析封面。
你给的这两个样本都是没有封面的，不应该会导致封面读取异常，我在demo上测试也没发现问题

> 可以解析封面，但解析歌名，专辑名等错误为“kuwo”。

这是标签的问题，那些标签内容就是kuwo，需要你编辑标签修正

**Comment by lyswhut** [comment]
可以试试 1.2.0-beta.13，这个版本修改了封面的读取方式

**Comment by zjqf2021** [comment]
> 你给的这两个样本都是没有封面的，不应该会导致封面读取异常，我在demo上测试也没发现问题
> 

测试发现，arm64-v8a bug仍存在：
  - app-v1.2.0-beta.13-arm64-v8a-release 仍然存在解析封面异常，点击播放栏后卡死。
  - app-v1.2.0-beta.13-universal-release解析封面正常，播放正常。
  - 目前手机系统应该是arm64 （HUAWEI EMUI10）

Uploading SVID_20231216_152243_1.mp4…

**Comment by zjqf2021** [comment]
Uploading SVID_20231216_152243_1.mp4…
