### ISSUE TITLE
[Bug]: beta13-universal个别在线歌曲解析封面异常导致卡死

### ISSUE THREAD

**Issue by zjqf2021** [lyswhut/lx-music-mobile#379]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

个别在线音乐：
- 获取在线音乐封面异常，显示为空白，点击播放栏会触发界面卡死
![Screenshot_20231216_183810_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/96340124/930556a2-d599-4d04-8fd2-82ad78e2fdee)
- 获取歌曲失败时，默认封面仍然会解析为空白，点击仍然会触发卡死。
![Screenshot_20231216_185238_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/96340124/10504bf0-1f49-42ae-95b7-dcfa71d960ad)

### 实际行为

解析封面异常，会导致点击播放栏触发卡死。

### Lx Music 版本

1.2.0 beta13-universal

### 操作系统版本

emui10 Android10

**Comment by lyswhut** [comment]
这应该与 https://github.com/lyswhut/lx-music-mobile/issues/378 相同
试试 1.2.0-beta.14是否已修复

**Comment by zjqf2021** [comment]
> 这应该与 #378 相同 试试 1.2.0-beta.14是否已修复

完美 完美
