### ISSUE TITLE
安卓移动版不能指定音乐目录

### ISSUE THREAD

**Issue by outsidesilence** [lyswhut/lx-music-mobile#38]
安卓版本：11
内置存储有个music目录，里面有下好的音乐。用手机系统自带播放器可以识别，lx-music-mobile不能指定音乐目录，不能识别里面的音乐。几个app公用一个music音乐，是很正常的情况。希望改进

**Comment by lyswhut** [comment]
目前还没有下载功能，也不支持添加播放本地歌曲，指定目录没意义
