### ISSUE TITLE
[Bug]:1.2.0 beta13-universal设置错误日志记录选项无法保存

### ISSUE THREAD

**Issue by zjqf2021** [lyswhut/lx-music-mobile#381]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

错误记录的设置可以正常保存

### 实际行为

设置-错误记录-勾选后重启app后恢复为未选中。
![Screenshot_20231217_130855_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/96340124/d44f297e-e604-45a1-affb-f2328b064aae)

### Lx Music 版本

1.2.0 beta13-universal

### 操作系统版本

emui10 Android10

### 附加信息

这个不会是保留的一个特性吧，对于临时记录异常倒也不错。

**Comment by lyswhut** [comment]
这是故意这样设置的，每次启动APP时日志记录设置默认处于关闭状态
