### ISSUE TITLE
[Bug]: 车机上没办法识别u盘

### ISSUE THREAD

**Issue by qdpatriotcn** [lyswhut/lx-music-mobile#383]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

播放u盘里的音乐。

### 实际行为

找不到u盘里的音乐

### Lx Music 版本

beta13

### 最后正常的版本

无

### 操作系统版本

车机安卓9

### 附加信息

在车机上使用，beta13版本。
![20231217_141206](https://github.com/lyswhut/lx-music-mobile/assets/105200583/f1c882dd-ba19-4862-8ffd-a86e714e1a83)
点击会报错。

**Comment by lyswhut** [comment]
试试 1.2.0-beta.15

**Comment by qdpatriotcn** [comment]
> 试试 1.2.0-beta.15

首先感谢这么快的修复。但是很不幸，刚才在车机上装了beta15，还是没办法发现u盘的路径。

https://github.com/lyswhut/lx-music-mobile/assets/105200583/87b338f5-37b3-46d3-8003-7e8a1f888b0d

我发了个操作的视频，您看下会不会对解决问题有帮助。无论如何，十分感谢。

**Comment by qdpatriotcn** [comment]
> 试试 1.2.0-beta.15

还有就是椒盐音乐可以识别我车机上的u盘，点击这个添加自定义文件夹，会弹出车机上自己的文件管理器，就可以选择车机上的文件夹来导入。好像是利用安卓的SAF框架。不知道会不会对你有帮助。上面写了其他播放器的名字，不知道可不可以。如果有不妥，告诉我，我会删掉。
![Screenshot_20231218-155708_Salt Player](https://github.com/lyswhut/lx-music-mobile/assets/105200583/4b258153-0fcc-4210-b602-f4120449eee5)

**Comment by lyswhut** [comment]
你U盘的路径是怎么样的呢？去文件管理随便找首U盘的歌曲查看下详情看看路径，
还有你外面播放栏怎么那么高，之前之前的版本也是这么高吗？

**Comment by qdpatriotcn** [comment]
> 你U盘的路径是怎么样的呢？去文件管理随便找首U盘的歌曲查看下详情看看路径， 还有你外面播放栏怎么那么高，之前之前的版本也是这么高吗？
> 
> 我在Android 10上测试内储卡、外接硬盘都可以正常读取，只是没有写入权限而已

 
这是在椒盐里，读取到的路径信息。
![20231219_154317](https://github.com/lyswhut/lx-music-mobile/assets/105200583/3a388f82-3c68-4c6b-88ed-d3cd1becff54)

你说的那么高的地方，是不是播放时候的进度条，我印象中，车机上一直是这样的。
![20231219_154402](https://github.com/lyswhut/lx-music-mobile/assets/105200583/11551de1-0a5f-4743-8b47-2416a8a5f6f2)

我的车机是安卓9。好多本地播放器都没办法读取u盘并播放。现在试过的，椒盐，AIMP，musicolet这三个，是可以的。椒盐也是从beta16，才开始可以的。

**Comment by qdpatriotcn** [comment]
> 你U盘的路径是怎么样的呢？去文件管理随便找首U盘的歌曲查看下详情看看路径， 还有你外面播放栏怎么那么高，之前之前的版本也是这么高吗？
> 
> 我在Android 10上测试内储卡、外接硬盘都可以正常读取，只是没有写入权限而已



这是我用文件管理器，u盘上的一首歌的信息

![20231219_155337](https://github.com/lyswhut/lx-music-mobile/assets/105200583/f831cd65-b655-4077-af06-8b570c390ca5)
![20231219_155349](https://github.com/lyswhut/lx-music-mobile/assets/105200583/ef465ea9-aa63-4f77-acd1-f491b7abe7fb)
![20231219_155401](https://github.com/lyswhut/lx-music-mobile/assets/105200583/2877abe4-5178-4d9d-a22f-d4ebece51ccb)

**Comment by lyswhut** [comment]
我花了两天时间研究了SAF，大概知道怎么读写文件了，但是SAF不提供`File`对象，导致依赖该对象的[歌曲标签库](http://www.jthink.net/jaudiotagger/)无法使用，对于这个问题我现在没有找到合适的解决方案，只找到了[这个](https://stackoverflow.com/a/60289272)，通过`/proc/self/fd/[fd]`的形式创建`File`对象并简单魔改了一下它，android 10测试后发现它只对内部存储的文件有效，类似可插拔的SD卡等外部存储设备会报没有读写权限的错误，另外在android 13上测试这种方式只能读取内部存储文件，没有写入权限。
另外，使用SAF读写文件等操作速度相比直接用File对象慢了非常非常多，现在非要通用实现的话，只能使用SAF将文件复制到私有目录后进行标签读写，有需要的话再将其覆盖回去，但这样效率会非常低下。

现在我想验证的一个问题是能不能在授予外部存储权限的情况下直接访问`/mnt/media_rw/xx`的目录，如果可以那就可以直接高性能的读取里面的标签了，但我手上没有这种设备，无法验证，下个版本我会加个打开路径的窗口，手动输入要打开的路径，到时候你可以试试把这个目录输进去能不能打开。

播放栏指的是外面的播放栏，不是播放详情页的播放栏。

**Comment by qdpatriotcn** [comment]
> 我花了两天时间研究了SAF，大概知道怎么读写文件了，但是SAF不提供`File`对象，导致依赖该对象的[歌曲标签库](http://www.jthink.net/jaudiotagger/)无法使用，对于这个问题我现在没有找到合适的解决方案，只找到了[这个](https://stackoverflow.com/a/60289272)，通过`/proc/self/fd/[fd]`的形式创建`File`对象并简单魔改了一下它，android 10测试后发现它只对内部存储的文件有效，类似可插拔的SD卡等外部存储设备会报没有读写权限的错误，另外在android 13上测试这种方式只能读取内部存储文件，没有写入权限。 另外，使用SAF读写文件等操作速度相比直接用File对象慢了非常非常多，现在非要通用实现的话，只能使用SAF将文件复制到私有目录后进行标签读写，有需要的话再将其覆盖回去，但这样效率会非常低下。
> 
> 现在我想验证的一个问题是能不能在授予外部存储权限的情况下直接访问`/mnt/media_rw/xx`的目录，如果可以那就可以直接高性能的读取里面的标签了，但我手上没有这种设备，无法验证，下个版本我会加个打开路径的窗口，手动输入要打开的路径，到时候你可以试试把这个目录输进去能不能打开。
> 
> 播放栏指的是外面的播放栏，不是播放详情页的播放栏。

非常感谢你的辛苦付出。我只能尽量提供详实的反馈。下个版本出了后，我再测试反馈。车机这个读写u盘的问题，我也搜索了好多，总体的感觉就是好像比较复杂。能够想象出解决这个问题有多复杂和麻烦。感谢你没有放弃。辛苦
 外面的播放栏一直都是那么高，我还一直觉得是特别为车机设计的，方便点击。

**Comment by lyswhut** [comment]
> 文件选择器允许（在旧系统）选择外置存储设备上的路径，长按存储卡按钮可显示手动输入存储路径的窗口

试试 1.2.0-beta.16，如果不行的话再看

**Comment by lyswhut** [comment]
v1.2.0-beta.17已支持安卓范围存储系统，支持选择外置存储路径，可以在文件选择器上的存储卡按钮选择

**Comment by qdpatriotcn** [comment]
> v1.2.0-beta.17已支持安卓范围存储系统，支持选择外置存储路径，可以在文件选择器上的存储卡按钮选择

不好意思，刚来看到。回头安装测试下，回来反馈。

**Comment by qdpatriotcn** [comment]
> v1.2.0-beta.17已支持安卓范围存储系统，支持选择外置存储路径，可以在文件选择器上的存储卡按钮选择

刚才试的beta18，已经可以了。十分感谢。
![20231224_141301](https://github.com/lyswhut/lx-music-mobile/assets/105200583/5eff6e84-5a74-436e-83f6-3cdfe2c4cb98)

添加歌曲的时候，会一直转圈圈。是不是可以考虑改成进度条或者一共识别多少歌曲，已经添加了多少首。要不然会不清楚到底是在添加歌曲，还是卡住了。我的才200多首。等了好一阵子。
还有就是确实感觉性能很吃紧，就是点开歌曲卡卡的，界面载入都会明显滞后，我的本地歌曲都是内嵌封面和歌词的。切换歌曲的时候，也是明显有卡顿的感觉，专辑封面载入滞后。是不是因为u盘传输速率的问题。

**Comment by lyswhut** [comment]
在文件选择界面转圈是因为在读取整个文件列表，
点开歌曲卡是指切歌的时候？还是指打开播放详情页？打开播放详情页的性能按理说不应该受到影响。
切歌封面载入慢可以用缓存的方式解决，但这无法解决首次播放歌曲慢的问题，只能解决第二次播放的载入问题。
终究揭底，这都是SAF读取目录速度慢，由于无法在外置存储设备直接使用File对象的问题，你可以试试将一两首歌曲复制到内部存储，使用非SAF（文件选择器上的路径不是以content://开头）的方式添加歌曲测试

**Comment by qdpatriotcn** [comment]
> 在文件选择界面转圈是因为在读取整个文件列表， 点开歌曲卡是指切歌的时候？还是指打开播放详情页？打开播放详情页的性能按理说不应该受到影响。 切歌封面载入慢可以用缓存的方式解决，但这无法解决首次播放歌曲慢的问题，只能解决第二次播放的载入问题。 终究揭底，这都是SAF读取目录速度慢，由于无法在外置存储设备直接使用File对象的问题，你可以试试将一两首歌曲复制到内部存储，使用非SAF（文件选择器上的路径不是以content://开头）的方式添加歌曲测试

好的，hug

**Comment by lyswhut** [comment]
1.2.0-beta.20优化了外置外置存储设备歌曲的封面读取性能，可以试试效果
