### ISSUE TITLE
[Bug]: 时长显示不全

### ISSUE THREAD

**Issue by StarVase** [lyswhut/lx-music-mobile#384]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

在收藏列表，歌词页面时长应显示xx：xx

### 实际行为

只显示xx：x
![Screenshot_20231218-000108_LX Music](https://github.com/lyswhut/lx-music-mobile/assets/63991487/789f0d64-8856-4d85-84e9-115249490344)

### Lx Music 版本

1.2.0 beta14 arm64 v8a

### 最后正常的版本

未见

### 操作系统版本

Android 13

**Comment by lyswhut** [comment]
什么厂商的设备？具体有哪些地方的文本被截断呢？

**Comment by lyswhut** [comment]
看起来与 https://github.com/facebook/react-native/issues/15114 相关，试试 1.2.0-beta.15 是否已解决

**Comment by StarVase** [comment]
> 什么厂商的设备？具体有哪些地方的文本被截断呢？

设备是小米 mi5
系统是pixelexperience13plus

**Comment by StarVase** [comment]
> 看起来与 https://github.com/facebook/react-native/issues/15114 相关，试试 1.2.0-beta.15 是否已解决

beta18中测试通过。感谢您的努力工作！
