### ISSUE TITLE
[Bug]: 导入歌单失败

### ISSUE THREAD

**Issue by cuddly-guacamole** [lyswhut/lx-music-mobile#385]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

![Screenshot_2023-12-18-10-55-04-354_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/58586966/dcbb79b5-1c59-4360-97e7-c9b40bed9087)

### 实际行为

![Screenshot_2023-12-18-10-55-32-876_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/58586966/b58c1e25-2828-4f59-93a7-bd1332227f3b)

### Lx Music 版本

1.2.0-beta.14 arm64-v8a

### 最后正常的版本

1.2.0-beta.8 arm64-v8a

### 操作系统版本

Android 13

**Comment by lyswhut** [comment]
已在 1.2.0-beta.15 修复
