### ISSUE TITLE
测试版beta7以后在软件停止运行后要过3秒左右歌曲才会停止播放

### ISSUE THREAD

**Issue by Aspyhyxia** [lyswhut/lx-music-mobile#386]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

软件杀掉后台后应该歌曲立即停止播放

### 实际行为

软件停止后过3秒，有时长达5秒才歌曲停止播放

### Lx Music 版本

1.2.0-beta.15-arm64-v8a

### 最后正常的版本

1.2.0-beta.7-arm64-v8a

### 操作系统版本

Android 13

**Comment by liziming987** [comment]
> ### 解决方案检查
> * [x]  我已阅读常见问题(https://lyswhut.github.io/lx-music-doc/mobile/faq)，并没有找到解决方案
> * [x]  我已搜索issue列表([https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=](https://github.com/lyswhut/lx-music-mobile/issues?utf8=%E2%9C%93&q=))，并没有发现类似的问题
> 
> ### 预期行为
> 软件杀掉后台后应该歌曲立即停止播放
> 
> ### 实际行为
> 软件停止后过3秒，有时长达5秒才歌曲停止播放
> 
> ### Lx Music 版本
> 1.2.0-beta.15-arm64-v8a
> 
> ### 最后正常的版本
> 1.2.0-beta.7-arm64-v8a
> 
> ### 操作系统版本
> Android 13
> 
> ### 附加信息
> _No response_

我的退出要10秒左右

**Comment by lyswhut** [comment]
这应该是音频卸载功能导致的，beta.7以后在播放器初始化时就开始启用音频卸载功能（之前是在屏幕关闭后），音频卸载是将音频解码从cpu卸载到专有硬件处理以节省应用耗电量，非正常退出（播放时强行关闭或者卸载应用）都可能会出现该问题。
退出应用建议使用lx内的退出功能，即通知栏的停止按钮或者软件内的退出按钮

**Comment by Aspyhyxia** [comment]
已解决

**Comment by SunshineboyZj** [comment]
beta16，强行退出应用（从后台关闭）后音乐不会停止，直到当前播放的这首歌放完

**Comment by SunshineboyZj** [comment]
> beta16，强行退出应用（从后台关闭）后音乐不会停止，直到当前播放的这首歌放完

不过有点奇怪的是，连接蓝牙耳机清掉后台音乐会立即停止播放；有线耳机和手机扬声器播放的音乐在清掉后台后则不会停止，直到当前播放的这首歌放完
