### ISSUE TITLE
[Bug]: 动态背景显示出错

### ISSUE THREAD

**Issue by cxg12** [lyswhut/lx-music-mobile#387]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

投屏到车联上时动态背景没有全屏显示，只显示一小块。还有这字体能不能再大点啊，我都把设置里的字体调到最大了

### 实际行为

![Screenshot_2023-12-19-07-59-46-42_1908217343](https://github.com/lyswhut/lx-music-mobile/assets/46776290/b1e2bf35-7365-46ab-8b2c-45704f9d0aac)

### Lx Music 版本

1.2.0-beta.15-arm64-v8a

### 操作系统版本

Android 12

**Comment by lyswhut** [comment]
1.2.0-beta.16做了一些处理，由于没有环境测试，不清楚能不能解决背景覆盖问题
字体小的问题暂不打算解决，不过可以尝试这个方案：https://github.com/lyswhut/lx-music-mobile/issues/358#issuecomment-1853182861

**Comment by cxg12** [comment]
> 1.2.0-beta.16做了一些处理，由于没有环境测试，不清楚能不能解决背景覆盖问题 字体小的问题暂不打算解决，不过可以尝试这个方案：[#358 (comment)](https://github.com/lyswhut/lx-music-mobile/issues/358#issuecomment-1853182861)

完美解决了，字体大小问题也好了
![Screenshot_2023-12-20-18-04-20-56_1781126972](https://github.com/lyswhut/lx-music-mobile/assets/46776290/56642854-c27b-488a-84d4-8b0e21f681da)
