### ISSUE TITLE
请求添加歌曲下载功能

### ISSUE THREAD

**Issue by lingtian152** [lyswhut/lx-music-mobile#39]
请求添加歌曲下载功能

**Comment by jswnlinyu** [comment]
如果有root，在/root/data/data/cn.toside.music.mobile/cache/trackplayer/“数字（随机数）”/下的文件复制出来，然后改成MP3就行。

**Comment by qw1324** [comment]
那无root呢

**Comment by jswnlinyu** [comment]
> 那无root呢

那就没法子了
