### ISSUE TITLE
[Bug]: 勾选跟随系统亮、暗模式切换主题后，系统切换暗色模式后排行榜、歌单列表文字消失

### ISSUE THREAD

**Issue by cxg12** [lyswhut/lx-music-mobile#390]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

系统切换暗色模式，文字颜色改变

### 实际行为

切换暗色模式后，歌单、排行榜列表文字直接消失；需要点设置后再点回去才能显示

### Lx Music 版本

1.2.0-beta.15

### 操作系统版本

Android 12

**Comment by lyswhut** [comment]
已在1.2.0-beta.16修复
