### ISSUE TITLE
[Feature]: 希望添加正在播放歌曲列表

### ISSUE THREAD

**Issue by HK7009** [lyswhut/lx-music-mobile#391]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望作者填加正在播放的歌曲列表

### 描述你想要的解决方案

这样比较方便切歌
非常感谢作者的付出

**Comment by zjqf2021** [comment]
临时列表就是啊

**Comment by HK7009** [comment]
> 临时列表就是啊

只有试听列表，临时列表在哪里啊

**Comment by zjqf2021** [comment]
> > 临时列表就是啊
> 
> 只有试听列表，临时列表在哪里啊
播放栏长按封面，可跳转到临时列表

**Comment by HK7009** [comment]
> > > 临时列表就是啊
> > 
> > 
> > 只有试听列表，临时列表在哪里啊
> 
> 播放栏长按封面，可跳转到临时列表

好的，找到了

**Comment by zjqf2021** [comment]
> > > > 临时列表就是啊
> > > 
> > > 
> > > 只有试听列表，临时列表在哪里啊
> > 
> > 
> > 播放栏长按封面，可跳转到临时列表
> 
> 好的，找到了

记得close这个issue
