### ISSUE TITLE
本地音乐播放时在软件内能看到封面，但在系统状态栏上不显示歌曲封面，已经确保歌曲文件内嵌了封面

### ISSUE THREAD

**Issue by Aspyhyxia** [lyswhut/lx-music-mobile#392]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望状态栏能够显示本地音乐歌曲的封面

### 实际行为

软件内显示，状态栏不显示

### Lx Music 版本

1.2.0-beta15-arm64-v8a

### 操作系统版本

Android 13

**Comment by zjqf2021** [comment]
APP设置里面需要设置一下通知栏显示封面

**Comment by lyswhut** [comment]
已在1.2.0-beta.16修复
