### ISSUE TITLE
[Feature]: 添加“关闭通过左右滑动的方式切换侧边栏页签”的功能

### ISSUE THREAD

**Issue by SunshineboyZj** [lyswhut/lx-music-mobile#397]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

可以自己选择关闭通过左右滑动的方式切换侧边栏页签

### 描述你想要的解决方案

左右滑动屏幕不会切换侧边栏页签

### 附加信息

这个灵敏度太高了，很容易误触发切换到其它页面。
比如我的收藏一不小心就切换到排行榜/设置页面了。

**Comment by lyswhut** [comment]
已在1.2.0-beta.18新增

**Comment by SunshineboyZj** [comment]
谢谢！

**Comment by SunshineboyZj** [comment]
> 已在1.2.0-beta.18新增

谢谢！
