### ISSUE TITLE
[Feature]: 三星应用商店出现同名同logo应用

### ISSUE THREAD

**Issue by zhuigu** [lyswhut/lx-music-mobile#398]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![1207_1703231878_hd](https://github.com/lyswhut/lx-music-mobile/assets/31404747/e8754f9c-7be2-4e7b-9cad-6589eeb39b47)
![1208_1703231879_hd](https://github.com/lyswhut/lx-music-mobile/assets/31404747/cc4ea8ed-691b-40cc-a670-ed1539b9f83f)

### 描述你想要的解决方案

可否上架三星应用商店

### 描述你考虑过的替代方案

无

### 附加信息

无

**Comment by helloplhm-qwq** [comment]
不会上架任何应用商店

**Comment by helloplhm-qwq** [comment]
> 不会上架任何应用商店

应用商店的一律是盗版，使用造成的任何损失我们不承担任何后果
