### ISSUE TITLE
升级到0.7.0版网易音乐打开最热歌单加载错误

### ISSUE THREAD

**Issue by git10135405** [lyswhut/lx-music-mobile#40]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述错误**

正常软件提示升级到0.7.0版本 网易音乐打开最热歌单加载错误

**Comment by lyswhut** [comment]
你所在网络连接到网易云服务器的问题，我这边是正常的

**Comment by git10135405** [comment]
> 你所在网络连接到网易云服务器的问题，我这边是正常的

上个版本不会，升级后才会

**Comment by ameaninglessname** [comment]
他指的应该是小芸音乐，我这边也打不开，小蜗可以

**Comment by lyswhut** [comment]
你是指歌单详情页吧？下载麻烦说清楚一点，这个确实是这次更新导致的，晚点修复它

**Comment by lyswhut** [comment]
此问题已在v0.7.1修复
