### ISSUE TITLE
[Bug]: 比亚迪车机无法选择自定义源

### ISSUE THREAD

**Issue by Titanchao** [lyswhut/lx-music-mobile#400]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

正常选择自定义源

### 实际行为

比亚迪车机选择自定义源，会跳转到内置文件浏览器，点击相应文件无法应用，只弹出编辑文件的选项，车机版本1.3

### Lx Music 版本

1.2.0-beta.17

### 最后正常的版本

1.1.1

### 操作系统版本

Android 10

**Comment by lyswhut** [comment]
具体是怎么样的呢？提供下视频？

**Comment by luo201227** [comment]
关掉基本设置的“使用系统文件选择器”
