### ISSUE TITLE
[Bug]: 听歌经常听一会儿，歌曲播放跳过一部分

### ISSUE THREAD

**Issue by TealLymn** [lyswhut/lx-music-mobile#403]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

解决Bug, 有一个好的听歌心情

### 实际行为

听歌时，常常听歌经常听到一会儿，歌曲播放跳过一部分，在听一些较长的歌，会跳好几次，歌词、播放进度也在倒退（使用六音音源）

### Lx Music 版本

1.2.0-beta.18

### 操作系统版本

HarmonyOS 3.0.0

**Comment by TealLymn** [comment]
仔细看了一下，歌词、播放进度在后退，且出现跳段现象

**Comment by lyswhut** [comment]
看 https://github.com/lyswhut/lx-music-mobile/issues/393

**Comment by TealLymn** [comment]
感谢落雪大大，问题已解决👌

**Comment by TealLymn** [comment]
> 看 #393

感谢落雪大大，问题已解决👌
