### ISSUE TITLE
系统解码器异常

### ISSUE THREAD

**Issue by StarVase** [lyswhut/lx-music-mobile#407]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

应该是系统原因，因为我是偶然发现在连接有线耳机时，所有调用系统解码器播放音乐的app都不能正常播放（包括但不限于卡顿，噪声，速度减慢，变调，啸叫），但是只有两个软件除外，就是上个release的lxmusic和musicolet。musicolet内置解码器，并且允许用户在系统解码器和内置解码器间切换。已证实，使用系统解码器会出现以上情况，而内置解码器不会。
lxmusic之前也可以正常解码，但自从上次从beta8直接更新到最新版本的beta18，解码也出现异常。
当我使用同一型号同一系统的其他手机进行测试时，遇到了同样的问题。

### 描述你想要的解决方案

希望加入软件内置解码器，允许用户手动选择解码器

### 描述你考虑过的替代方案

使用lxmusic完整加载音乐后从数据目录找到缓存，导出后使用musicolet播放

**Comment by lyswhut** [comment]
尝试关闭音频卸载
https://github.com/lyswhut/lx-music-mobile/issues/393

**Comment by StarVase** [comment]
> 尝试关闭音频卸载
> https://github.com/lyswhut/lx-music-mobile/issues/393

问题解决，不过我有个疑问，希望解答：
这个音频卸载的作用和原理是什么？
感谢！

**Comment by lyswhut** [comment]
https://developer.android.com/guide/topics/media/exoplayer/battery-consumption?hl=zh-cn#audio-playback

> Audio offload allows audio processing to be offloaded from the CPU to a dedicated signal processor.

看行为是将音频数据推送到设备上的专有硬件模块处理
