### ISSUE TITLE
系统栏和背景沉浸问题

### ISSUE THREAD

**Issue by StarVase** [lyswhut/lx-music-mobile#408]
![Screenshot_20231224-235058_LX Music.png](https://github.com/lyswhut/lx-music-mobile/assets/63991487/d3a00b64-a4fd-4996-8598-f9ad8e9792b8)

理想情况下，状态栏图标的颜色应根据背景颜色来改变，在黑色背景下应显示为白色图标，但是实际上显示为黑色，导致状态栏图标无法看清。

应用底栏的颜色和侧滑栏也应该有动态背景，可以设置背景遮罩来区分高度。

系统导航栏在暗色主题下显示为白色有点不合适，如果react框架支持沉浸导航栏的话也可以像状态栏那样优化。

**Comment by lyswhut** [comment]
你截图上的状态栏颜色不是正常的吗，
切换亮/暗主题后，下面的系统手势导航需要重启APP才可以，试了下RNN好像无法在已打开的屏幕更新颜色设置

**Comment by StarVase** [comment]
> 你截图上的状态栏颜色不是正常的吗， 切换亮/暗主题后，下面的系统手势导航需要重启APP才可以，试了下RNN好像无法在已打开的屏幕更新颜色设置

可是可是，我截图前确实是黑色的文字，鬼知道截屏时候systemui在发什么癫

**Comment by StarVase** [comment]
原生开发中，activity.recreate()方法可以重构activity，不知道你的框架可不可以用这个方法
