### ISSUE TITLE
[Bug]: 酷狗概念版分享的歌单链接无法打开

### ISSUE THREAD

**Issue by chenp1204** [lyswhut/lx-music-mobile#409]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

歌单链接正常打开显示歌单列表

### 实际行为

同桌面版问题 
https://github.com/lyswhut/lx-music-desktop/issues/1735

![image](https://github.com/lyswhut/lx-music-mobile/assets/29192482/fe9748e0-6576-482a-b495-e31b121d2980)

![image](https://github.com/lyswhut/lx-music-mobile/assets/29192482/949f2d00-dd4e-42a8-97d1-ecff767b699a)

测试歌单地址：  
https://t1.kugou.com/9Qu2h58BiV2

### Lx Music 版本

1.2.0-beta-16

### 操作系统版本

miui 14  android 13

**Comment by lyswhut** [comment]
目前还没有支持酷狗概念版歌单导入

**Comment by chenp1204** [comment]
> 目前还没有支持酷狗概念版歌单导入

好的 辛苦大佬

**Comment by wndlsj** [comment]
不如 你把酷狗概念版的歌单 导入酷狗 然后再从酷狗导入呢
