### ISSUE TITLE
[Bug]: 启动音频卸载

### ISSUE THREAD

**Issue by cxg12** [lyswhut/lx-music-mobile#416]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

开启音频卸载，能够自动播放下一首

### 实际行为

开启音频卸载大概率出现不能自动播放下一首同时歌词还加载不出来，关闭音频卸载就正常了

### Lx Music 版本

beta.19

### 操作系统版本

投屏到car+车联的

**Comment by lyswhut** [comment]
播放器与歌词的逻辑是分开的，从原理上说这两者不会相互干扰，
我对投屏没有什么经验，无法从你的描述判断出是什么问题导致的，
音频卸载依赖的是设备及系统功能，若无法使用那就只能管关闭它
