### ISSUE TITLE
[Bug]: 酷我的一些歌，歌词总是获取失败

### ISSUE THREAD

**Issue by TealLymn** [lyswhut/lx-music-mobile#417]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

酷我源的一些歌的歌词可以显示

### 实际行为

用酷我源听时，能听但歌词常常获取失败，且使用电脑端也一样，清理歌词缓存后仍然无效

https://github.com/lyswhut/lx-music-mobile/assets/152773889/0c260e9e-57a6-4ad1-b328-1989867679e9

### Lx Music 版本

1.2.0-beta.21 arm64-v8a

### 操作系统版本

HarmonyOS 3.0.0

### 附加信息

使用六音音源

**Comment by lyswhut** [comment]
这是因为之前酷我带翻译的歌词解析出来有问题，翻译跟原文对不上，于是存在翻译的歌词直接丢弃了，刚才看了下似乎现在大部分歌曲又都正常了，下个版本加回来

**Comment by TealLymn** [comment]
感谢大大，期待下一个beta

**Comment by lyswhut** [comment]
试试1.2.0-beta22

**Comment by TealLymn** [comment]
> 试试1.2.0-beta22


https://github.com/lyswhut/lx-music-mobile/assets/152773889/ea763d27-8676-4d8f-991b-09adb932eeb9

还是有个酷我的歌没有歌词 (已更新1.20-beta22)

**Comment by lyswhut** [comment]
试试1.2.0-beta23

**Comment by TealLymn** [comment]
> 试试1.2.0-beta23

感谢大大，问题已解决
