### ISSUE TITLE
【Bug】通知栏进度条未正常显示

### ISSUE THREAD

**Issue by wootifer** [lyswhut/lx-music-mobile#42]
## **描述错误**
小米11通知栏进度条未正常显示

## **重现**
必现

## **预期行为**
进度条时间能够与app歌曲播放进度同步

## **截图**
![微信图片_20210830205417](https://user-images.githubusercontent.com/26326251/131342316-318f508a-c477-428f-8b1b-0cd91b4ae8ed.jpg)
![微信图片_20210830205406](https://user-images.githubusercontent.com/26326251/131342346-822a4355-dbcd-490e-82cc-cb05a4d20a09.jpg)
![微信图片_20210830205348](https://user-images.githubusercontent.com/26326251/131342362-833a3a94-f04c-4272-b303-b932edd99913.jpg)

## **环境：**
  -操作系统及版本：MIUI12.5 开发版 基于Android11
  -软件安装包及版本：lx-music-mobile-v0.7.1-universal.apk

**Comment by lyswhut** [comment]
这个通知栏进度条安卓11才有的，目前没有适配，下个版本会适配它

**Comment by wootifer** [comment]
> 这个通知栏进度条安卓11才有的，目前没有适配，下个版本会适配它

哦哦，好嘞，辛苦啦！

**Comment by lyswhut** [comment]
你可以来这里下载测试版安装试下：https://github.com/lyswhut/lx-music-mobile/actions/runs/1189092703

**Comment by wootifer** [comment]
> 你可以来这里下载测试版安装试下：https://github.com/lyswhut/lx-music-mobile/actions/runs/1189092703

嗯嗯，已经装上了，进度条现在正常了。

**Comment by lyswhut** [comment]
已在v0.8.0添加
