### ISSUE TITLE
这已经解决了：https://github.com/lyswhut/lx-music-desktop/issues/1762

### ISSUE THREAD

**Issue by xiaoyaoyufeng0** [lyswhut/lx-music-mobile#439]
这已经解决了：https://github.com/lyswhut/lx-music-desktop/issues/1762

_Originally posted by @anshe80 in https://github.com/lyswhut/lx-music-mobile/issues/435#issuecomment-1921465013_

**Comment by zjqf2021** [comment]
我测试了 不好用的
