### ISSUE TITLE
[Feature]: 音乐源 能否通过 cdn 、 nas、网盘等在线方式添加呢 ？

### ISSUE THREAD

**Issue by zhz-we** [lyswhut/lx-music-mobile#447]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

音乐源 能否通过 cdn 、 nas、网盘等在线方式添加呢 ？

开货车的朋友不懂操作，音乐源失效后不好意思麻烦我，每次都等回来后才找我要...

### 描述你想要的解决方案

音乐源 能否通过 cdn 、 nas、网盘等在线方式添加呢 ？

谢谢 🙏

**Comment by lyswhut** [comment]
v1.3.0添加http链接的形式导入
