### ISSUE TITLE
[Bug]: APP在横屏模式下显示不正常

### ISSUE THREAD

**Issue by ad8677** [lyswhut/lx-music-mobile#463]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

最开始用的1.2.0 beta.3版本，软件显示是正常的，显示区域不会到顶部状态栏去
![1709685699613271184870477432061](https://github.com/lyswhut/lx-music-mobile/assets/162322676/991824b0-d35e-4bee-8a65-233472823a01)

### 实际行为

更新1.2.0正式版本后，显示不正常，软件显示区域跑到状态栏去了，导致部分功能无法点击，搜索界面的“歌单”和“歌曲”按钮因为和状态栏重叠导致无法点击，经测试，最终正常版本为beta15.从beta16开始全部有问题。
![17096858366841047835046622472341](https://github.com/lyswhut/lx-music-mobile/assets/162322676/6466bb53-f8ba-4b6a-9d3e-5ff76b23a1c3)
![17096858642561512194260939070109](https://github.com/lyswhut/lx-music-mobile/assets/162322676/c718454a-e56c-4962-9750-aa847f0e2172)
![17096860140932724846281170049590](https://github.com/lyswhut/lx-music-mobile/assets/162322676/bbe5401d-c1df-424d-8fb2-7bd2445e4199)

### Lx Music 版本

1.2.0 beta16

### 最后正常的版本

1.2.0 beta15

### 操作系统版本

安卓11

**Comment by ad8677** [comment]
![20240318_083455](https://github.com/lyswhut/lx-music-mobile/assets/162322676/c89788cb-6bdc-4771-86df-7a302cf80cce)
![20240318_083513](https://github.com/lyswhut/lx-music-mobile/assets/162322676/d3511c77-faa5-45e2-be76-ea416e82ccdf)
![20240318_084044](https://github.com/lyswhut/lx-music-mobile/assets/162322676/6a2ad230-d5c4-453f-92d8-bc1144072c03)
最新的测试版1.3.0 beta1已经解决了，点赞！👍

**Comment by jy02919061** [comment]
请问你的车机上，数据同步可以用吗？我的在车机上点击开启没有反应

**Comment by ad8677** [comment]
> 请问你的车机上，数据同步可以用吗？我的在车机上点击开启没有反应

同步服务地址设置好了吗？
