### ISSUE TITLE
打开设置出现问题

### ISSUE THREAD

**Issue by jswnlinyu** [lyswhut/lx-music-mobile#47]
安卓6.0.1,armv7打开设置出错
![Screenshot_20210906-232327](https://user-images.githubusercontent.com/53430542/132283339-61fa7686-2cfa-48bd-b05e-4a905652242e.png)
![Screenshot_20210906-231945](https://user-images.githubusercontent.com/53430542/132283347-d86d025d-0d40-4abb-b6c1-eaab4affaabf.png)
![Screenshot_20210906-231950](https://user-images.githubusercontent.com/53430542/132283350-9ea081b9-0626-411a-b8a1-a1b24bf9e983.png)
![Screenshot_20210906-232010](https://user-images.githubusercontent.com/53430542/132283351-94822267-c79a-4faf-9189-0c9986dd6976.png)

**Comment by jswnlinyu** [comment]
附：版本lx-music-mobile-v0.8.0-universal.apk

**Comment by jswnlinyu** [comment]
> 试一下这个版本：https://github.com/lyswhut/lx-music-mobile/actions/runs/1211508760
> 需要注意的是，低版本安卓不一定可以用

谢谢大佬，我试试

**Comment by jswnlinyu** [comment]
> 试一下这个版本：https://github.com/lyswhut/lx-music-mobile/actions/runs/1211508760
> 需要注意的是，低版本安卓不一定可以用

解决了，谢谢大佬

**Comment by lyswhut** [comment]
已在v0.8.1修复
