### ISSUE TITLE
导入音源时显示没有文件怎么办啊

### ISSUE THREAD

**Issue by tuuuuuuoi** [lyswhut/lx-music-mobile#473]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

我已经下载过开源文件了，但是就是在最后导入的时候找不到文件，洛雪是有手机类型的限制吗，我的手机是oppo reno8

### 描述你想要的解决方案

,

### 描述你考虑过的替代方案

,

### 附加信息

![Screenshot_2024-03-24-02-02-31-74_176161be900e0e29934afca83eb113f8](https://github.com/lyswhut/lx-music-mobile/assets/159711701/81f15c51-5001-4bd3-9d56-a2d6ae68b531)

**Comment by zhongwen-4** [comment]
刷新一下试试（）

**Comment by tuuuuuuoi** [comment]
> 刷新一下试试（）

还是不行啊

**Comment by mis-u** [comment]
你这。。都没找到存放音源的文件夹，肯定不行啊  点那几条横杠去找

**Comment by xiaoheihei111** [comment]
有咩有能用的可靠的源啊 我这进去一首歌都播放不了

**Comment by tuuuuuuoi** [comment]
> 有咩有能用的可靠的源啊 我这进去一首歌都播放不了

**Comment by tuuuuuuoi** [comment]
> > 有咩有能用的可靠的源啊 我这进去一首歌都播放

> > 有咩有能用的可靠的源啊 我这进去一首歌都播放不了

https://raw.niuma666bet.buzz/Huibq/keep-alive/master/render_api.js用这个在线导入
