### ISSUE TITLE
如何编写加密音源？

### ISSUE THREAD

**Issue by hwxlikemi** [lyswhut/lx-music-mobile#484]
加密的目的：别人不能改个描述就拿音源拿去卖钱之类的

**Comment by lyswhut** [comment]
可以通过 `globalThis.lx.currentScriptInfo.rawScript` 拿到当前脚本源码检查头部注释之内的内容是否被篡改

**Comment by hwxlikemi** [comment]
> 可以通过 `globalThis.lx.currentScriptInfo.rawScript` 拿到当前脚本源码检查头部注释之内的内容是否被篡改

您好，请问能再讲详细一点吗？
谢谢。

**Comment by hwxlikemi** [comment]
> 可以通过 `globalThis.lx.currentScriptInfo.rawScript` 拿到当前脚本源码检查头部注释之内的内容是否被篡改

建议将这个写在lx music的文档里
