### ISSUE TITLE
二次启动闪退

### ISSUE THREAD

**Issue by qw1324** [lyswhut/lx-music-mobile#5]
第二次启动lx音乐会闪退，清理缓存也是一样

手机型号: Oneplus 8T

**Comment by lyswhut** [comment]
所用软件版本、系统版本呢？
没有崩溃弹窗？

**Comment by HHint** [comment]
同第二次启动会闪退，卸载重装也闪退。软件版本0.1.7 系统版本miui 12.0.21 没有弹窗 打开就闪退

**Comment by qw1324** [comment]
> 所用软件版本、系统版本呢？
> 没有崩溃弹窗？
> 可以的话提供下录屏？


https://user-images.githubusercontent.com/49418651/119150452-759ce800-ba1c-11eb-92a0-7f1669a4a399.mp4



闪退录屏
无闪退弹窗

**Comment by lyswhut** [comment]
试过universal版没有？用这个版本会这样吗？有小部分人遇到这个问题，但是我这边重现不出来，没办法调试

**Comment by lyswhut** [comment]
试下0.3.1版本看看有没有错误日志，之前的版本崩溃日志处理会导致app崩溃。。。

**Comment by qw1324** [comment]
> 试过universal版没有？用这个版本会这样吗？有小部分人遇到这个问题，但是我这边重现不出来，没办法调试

这个版本我还没试过

**Comment by qw1324** [comment]
> > 试过universal版没有？用这个版本会这样吗？有小部分人遇到这个问题，但是我这边重现不出来，没办法调试
> 
> 这个版本我还没试过 我试试看

我先用这个版本一段时间 如果还会出现闪退 我会反馈给你

**Comment by qw1324** [comment]
没遇到闪退问题 关啦~~~~~~
