### ISSUE TITLE
适配Android TV。armeabi-7a，android 4.4.2，API 19

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#50]
**解决方案检查**

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

适配Android TV。armeabi-7a，android 4.4.2，API 19
适配大屏幕，添加【调整app界面字体百分比】功能，支持200%的字体大小，以便能看清电视屏幕中app界面的文字。

**描述您考虑过的替代方案**

适配Android TV。armeabi-7a，android 4.4.2，API 19
适配大屏幕，添加【调整app界面字体百分比】功能，支持200%的字体大小，以便能看清电视屏幕中app界面的文字。

**其他内容**

适配Android TV。armeabi-7a，android 4.4.2，API 19
适配大屏幕，添加【调整app界面字体百分比】功能，支持200%的字体大小，以便能看清电视屏幕中app界面的文字。

**Comment by lyswhut** [comment]
软件所用模块原因，不支持低于Android 5的版本
armeabi-7a自行在[Releases](https://github.com/lyswhut/lx-music-mobile/releases)下载
Android TV可以运行，但是不计划适配遥控器操作，需要鼠标才能操作

**Comment by fanlushuai** [comment]
没有遥控器，没有灵魂呀作者
