### ISSUE TITLE
[Bug]: 导入歌单后播放一次后再重启就会启动失败

### ISSUE THREAD

**Issue by niumadajiang1** [lyswhut/lx-music-mobile#500]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

软件导入歌单播放一次后再重启就会引导失败

### 实际行为

软件导入歌单播放一次后再重启就会引导失败
![Uploading Screenshot_2024-05-04-14-30-45-104_cn.toside.music.mobile.jpg…]()
![Uploading Screenshot_2024-05-04-14-30-45-104_cn.toside.music.mobile.jpg…]()

### Lx Music 版本

1.4.0 arm64-v8a

### 操作系统版本

Android 12

### 附加信息

![Screenshot_2024-05-04-14-30-42-968_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/107527071/30eb18e8-4089-4627-b0d4-ec5d2ffe6b9b)
![Screenshot_2024-05-04-14-30-42-968_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/107527071/f7129344-44cf-4ce0-8e83-dba545ced2a8)
![Screenshot_2024-05-04-14-30-42-968_cn toside music mobile](https://github.com/lyswhut/lx-music-mobile/assets/107527071/bdb38c89-5d60-489b-ad0c-450e60647a54)

**Comment by lyswhut** [comment]
提供一下详细的重现步骤
导入某个歌单才会这样？是的话提供一下歌单链接？

**Comment by niumadajiang1** [comment]
[[导入的是我的网易云歌单，以及一些网易个人歌单，我可以把打包的备份文件发给您。导入音源后，执行第一次导入歌单后是正常使用的，重启软件后就会报错
[Uploading lx_datas_v2.zip…]()

**Comment by niumadajiang1** [comment]
[Uploading lx_datas_v2.zip…]()

**Comment by lyswhut** [comment]
你这文件没上传成功

**Comment by niumadajiang1** [comment]
https://easylink.cc/ncft5d录屏操作视频简易云链转的，建议用电脑看，他用手机会跳转vx小程序，歌单文件在下面
[lx_datas_v2.zip](https://github.com/lyswhut/lx-music-mobile/files/15428605/lx_datas_v2.zip)
https://easylink.cc/sy7k99

**Comment by niumadajiang1** [comment]
https://easylink.cc/ncft5d
录屏操作视频简易云链转的，建议用电脑看，他用手机会跳转vx小程序，歌单文件在下面]

[lx_datas_v2.zip](https://github.com/lyswhut/lx-music-mobile/files/15428650/lx_datas_v2.zip)

https://easylink.cc/sy7k99

**Comment by niumadajiang1** [comment]
这个会不会是我手机问题，但是其他软件都正常，我试过好几个lx-music的版本都有问题

**Comment by niumadajiang1** [comment]
您好，应该是歌单问题，不导入歌单文件的话没问题，但是我用pc端的同步后同步歌单也会这样报错，会不会是网易喜欢的那个歌单的问题，那个歌单歌曲数目超过了1000首

**Comment by lyswhut** [comment]
视频中出现导入备份文件后再次启动会报错，上面的备份文件跟视频中的不是同一个吧？现在是导入备份后更新歌单会出现问题吗

**Comment by niumadajiang1** [comment]
是同一个，不论是同步或者导入备份，更新这个用cookie在pc端建的网易云个人我的喜欢里歌单就会报错。那个歌单名字叫A夜深且网易喜欢的歌单

**Comment by lyswhut** [comment]
清理下APP数据，安装 1.3.0-beta.1 试试，
这个问题是账号的token获取没有按照文档写的来，传了包含非法字符的数据进去导致的

**Comment by niumadajiang1** [comment]
好的好的谢谢
