### ISSUE TITLE
[Bug]: 1.4.0播放界面歌词滚动不正常

### ISSUE THREAD

**Issue by Phoenixoftree** [lyswhut/lx-music-mobile#518]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

播放界面歌词正常滚动

### 实际行为

歌词界面在首句重复性上下弹跳，无法正常滚动。但正常显示当前正在播放的歌词，且其他界面的歌词（迷你播放栏、桌面歌词）显示正常。
![Screenshot_20240601-131942](https://github.com/lyswhut/lx-music-mobile/assets/171405199/d9278953-776e-42de-be68-5b047502d2ca)

### Lx Music 版本

1.4.0 arm64-v8a

### 最后正常的版本

1.3.0 arm64-v8a

### 操作系统版本

Android 14

**Comment by lyswhut** [comment]
试试1.4.1
