### ISSUE TITLE
[Feature]:歌曲去重

### ISSUE THREAD

**Issue by Hnto1s** [lyswhut/lx-music-mobile#535]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

经常听到喜欢的歌就会加入歌单，但是会发现偶尔有重复的。所以全部找很麻烦，希望可以增加歌曲去重功能。

### 描述你想要的解决方案

希望可以增加歌单去重功能，可以嘛

### 描述你考虑过的替代方案

我是小白不懂。

### 附加信息

我是小白不懂

**Comment by ameaninglessname** [comment]
应该是不同音源的，

有自带重复测，你现在也不能把同一首歌加到列表两次

**Comment by lyswhut** [comment]
已在v1.5.0新增
