### ISSUE TITLE
[Bug]: 同步功能异常

### ISSUE THREAD

**Issue by windeling** [lyswhut/lx-music-mobile#542]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

PC正常与手机进行同步

### 实际行为

![image](https://github.com/lyswhut/lx-music-mobile/assets/142467582/14cc4937-b58a-48e1-8382-ee4e472e2641)
同步无法进行，PC和手机浏览器访问对应网址均提示禁止。
已解除AP隔离，已关闭所有windows网络防火墙，已关闭杀毒软件。
后面还断开了公网连接。

### Lx Music 版本

2.4

### 操作系统版本

Android 10

**Comment by windeling** [comment]
神奇的是，我将端口改为24500后等了一会又可以连接上了。
手表一次就行，手机要多次尝试

**Comment by windeling** [comment]
神奇的是，我将端口改为24500后等了一会又可以连接上了。
手表一次就行，手机要多次尝试。

**Comment by T-wilight** [comment]
兄弟你是天才，我也是折腾几个月，每次都没折腾上，改个端口今天突然成了，莫名其妙的之前明明ping和hello都可以，防火墙也关了就是秒failed，这会同步成功了再之后试了试ping居然是失败的，，我大为震撼，但是同步成了就好，折腾死我了

**Comment by windeling** [comment]
> 兄弟你是天才，我也是折腾几个月，每次都没折腾上，改个端口今天突然成了，莫名其妙的之前明明ping和hello都可以，防火墙也关了就是秒failed，这会同步成功了再之后试了试ping居然是失败的，，我大为震撼，但是同步成了就好，折腾死我了

真是奇怪，而且这个原始端口也没有应用程序占用，但是就是不行。
