### ISSUE TITLE
[Feature]: 希望能添加一个对汽水音乐的支持

### ISSUE THREAD

**Issue by AlisaZZu** [lyswhut/lx-music-mobile#548]
### 解决方案检查

- [x] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

汽水音乐的音源

### 描述你想要的解决方案

可以导入汽水音乐的歌单

**Comment by hwxlikemi** [comment]
不太现实的想法。。。

**Comment by hwxlikemi** [comment]
自己动手丰衣足食
