### ISSUE TITLE
[Feature]: 希望能加一个快速定位到当前歌曲的小按钮

### ISSUE THREAD

**Issue by lackoxy** [lyswhut/lx-music-mobile#550]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

本人的收藏夹内的歌曲数量比较多，每次想查看当前歌曲的上下歌曲是什么时经常要疯狂下滑才能找到。

### 描述你想要的解决方案

在收藏夹页能添加一个很小的按钮用于快速定位当前歌曲

**Comment by 63684** [comment]
长按播放栏当前正在播放音乐图片即可定位所在位置

**Comment by lackoxy** [comment]
> 长按播放栏当前正在播放音乐图片即可定位所在位置

感謝
