### ISSUE TITLE
[Bug]: 关于音源混淆后在安卓上无法使用

### ISSUE THREAD

**Issue by LookStars** [lyswhut/lx-music-mobile#551]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

能正常初始化JS音源，听音乐

### 实际行为

![DAE9E9FD2510F4E49E011E7134D24648](https://github.com/user-attachments/assets/200eb8a8-d3ec-4ed0-9371-d72c00a34d0b)

### Lx Music 版本

lx-music-mobile-v1.4.2-arm64-v8a.apk

### 最后正常的版本

无

### 操作系统版本

HarmonyOS 4.2.0

### 附加信息

该音源通过JS混淆后在手机端无法正常使用，windows上是都可以正常使用的

**Comment by feihuafu** [comment]
六音也是混淆啊，你可以参考
