### ISSUE TITLE
[Beta Bug]: 从安卓播放器页面点击进去报错

### ISSUE THREAD

**Issue by 2096779623** [lyswhut/lx-music-mobile#562]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

无报错

### 实际行为

https://github.com/user-attachments/assets/83b1b283-9aa1-4e2c-94f5-3c56925d6a63

怀疑跟这个commit有关： 
 https://github.com/lyswhut/lx-music-mobile/commit/1728d7fc78b6a8738fa6890e4334ff1e05d0f567#diff-1448771819e2493401b0a06342dee4d62abd63c63b6b4a6a1aae9a80e398d673R38
**运行日志里面不会记录下这个报错**
### Lx Music 版本

1.6.0-beta.1 arm64v8a

### 最后正常的版本

1.5.0 arm64v8a

### 操作系统版本

Android 13

**Comment by lyswhut** [comment]
试试 1.6.0-beta.2

**Comment by 2096779623** [comment]
> 试试 1.6.0-beta.2

修好了 👍
