### ISSUE TITLE
例如：添加退出播放功能……

### ISSUE THREAD

**Issue by lshilshi** [lyswhut/lx-music-mobile#57]
**解决方案检查**

- [ ] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [ ] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述您想要的解决方案**

机器Oneplus 7Pro，H2OS 9.0系统
非重度音乐用户，使用频率一般

现有的Notification上只有播放/ 停止，上一曲。下一曲功能
不能在不需要时候停止播放并退出APP
只能每次划掉APP后台或者去Force Stop，十分不方便，还是是我wo没找到功能？

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
你看到的是mini状态通知栏吧？完整通知栏有正方形的停止按钮，按了会退出应用，还有播放进度条

**Comment by lshilshi** [comment]
> 你看到的是mini状态通知栏吧？完整通知栏有正方形的停止按钮，按了会退出应用，还有播放进度条

晕了，因为其它音乐app的退出（X）一般单独在右上角
所以这个正方形的按钮此前都忽略了

而且没习惯
之前要停止退出app，都是按双竖暂停，然后长按Notification，进应用详情页面，再force stop

谢谢解答！
