### ISSUE TITLE
退出App后，音乐无法自动停止

### ISSUE THREAD

**Issue by wang-y** [lyswhut/lx-music-mobile#580]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

上滑退出App后(指结束后台任务)，停止音乐播放

### 实际行为

在音乐播放时直接上滑退出App后，音乐不会被停止，只能重新进入然后点击播放再暂停，然后退出app

### Lx Music 版本

1.6.0 arm64-v8a

### 操作系统版本

Android 14

### 附加信息

手机型号为oppofindx6pro系统版本目前为最新

**Comment by zhongwen-4** [comment]
尝试关闭**启用音频卸载**

**Comment by wang-y** [comment]
> 尝试关闭**启用音频卸载**

确实可以了
