### ISSUE TITLE
[Bug]: 在车机系统中跟随系统亮/暗无效果

### ISSUE THREAD

**Issue by xiaoyi510** [lyswhut/lx-music-mobile#591]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

希望在车机中支持
目前车机系统为嘟嘟车机 
安卓13 

设置勾选后无效果,目前询问多个车主其他电车的车机也有不支持此功能的
PS:在安卓手机中有效果

### 实际行为

无反应

### Lx Music 版本

lx-music-mobile-v1.6.0-universal.apk

### 操作系统版本

安卓 13

**Comment by liuzhenghang** [comment]
bro，你的嘟嘟车机歌词显示正常吗，嘟嘟目前不适配lx，歌词不同步
