### ISSUE TITLE
[Feature]: 这个音乐播放怎么能设置的显示进度条，设备iQOOneo9

### ISSUE THREAD

**Issue by tintin0414** [lyswhut/lx-music-mobile#606]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

![Screenshot_20241011_215723](https://github.com/user-attachments/assets/d7604b2d-f03a-425f-a710-9bbddfec2a97)

### 描述你想要的解决方案

我以前用的小米有这个进度条但是换到iqoo以后没了，我想问一下这个怎么能设置的有进度条或者是第三方什么的软件也行

**Comment by zhongwen-4** [comment]
那就继续用小米（）
