### ISSUE TITLE
在ipv6的网络下无法播放音乐,一直卡在获取url

### ISSUE THREAD

**Issue by k631583871** [lyswhut/lx-music-mobile#61]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述错误**

在使用ipv6的网络下,无法播放新添加的音乐, 一直卡在 获取url

现在解决方式是使用vpn连接一个ipv4的服务器,使用ipv4的网络正常

**环境：**
  -操作系统及版本：[Android 11 , MIUI 12.5]
  -软件安装包及版本：[0.9.1]

**Comment by k631583871** [comment]
114.114.114.114 已经可以正常解析域名

**Comment by Mc-GrowlR** [comment]
电脑端开启ipv6也会出现此类情况，但是开启代理的话即可正常使用
