### ISSUE TITLE
平板无法显示评论

### ISSUE THREAD

**Issue by shanyan-wcx** [lyswhut/lx-music-mobile#62]

**Comment by lyswhut** [comment]
重现步骤是怎样的？附上截图？

**Comment by shanyan-wcx** [comment]
![Screenshot_20211220_124433_cn toside music mobile](https://user-images.githubusercontent.com/58252651/146725369-357ecc7b-ef92-4c88-bf98-a23191c70b6f.jpg)
正常播放就没有评论选项

**Comment by lyswhut** [comment]
横屏的评论入口忘了加了，下个版本补上

**Comment by lyswhut** [comment]
已在v0.10.0新增此功能
