### ISSUE TITLE
[Bug]: byd车机安装后，无法导入音源

### ISSUE THREAD

**Issue by XiewzHub** [lyswhut/lx-music-mobile#630]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

导入音源时，能正常读取文件并初始化成功

### 实际行为

在选择本地导入音源选项后，跳转到车机自带的文件管理系统，选择音源却只能打开音乐文件，无法跳转回lxmusic进行下一步初始化。
以前1.0.2的版本没有这个问题，因为那版导入时，不会跳转到车机自带的文件管理，而是软件内支持浏览文件，选中后能正常导入音源。

### Lx Music 版本

v1.6.0

### 最后正常的版本

v1.0.2

### 操作系统版本

Android 10

**Comment by lyswhut** [comment]
https://github.com/lyswhut/lx-music-mobile/issues/418#issuecomment-1874839337
