### ISSUE TITLE
[Bug]: 自编写自搭建了一个音源，在PC端（版本2.9）表现正常，在Android端（版本1.2-1.7-beta.0）无法正常使用

### ISSUE THREAD

**Issue by 1qingfeng-1** [lyswhut/lx-music-mobile#635]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

自编写自搭建了一个自定义音源，PC端和Android端添加该自定义音源后，可正常使用。

### 实际行为

1. 自编写自搭建了一个自定义音源，见附录
2. PC端导入该音源后后**可正常使用**
- PC端正常使用
![image](https://github.com/user-attachments/assets/36e84cd6-821d-4622-a35c-df9da4f5f729)
- 音源服务端log显示
![image](https://github.com/user-attachments/assets/c1e0e4c9-9505-4422-b63b-e2a0b033374f)
3. Android端App导入该音源后**无法使用**
- Android端App导入该音源，提示初始化成功，清除缓存，切歌后很快就提示换源失败， 且音源服务端无Log显示，疑似手机与音源服务器无法通信，但实际手机和PC已经处于同一局域网段下，手机浏览器可正常打开音源url，怀疑App js 环境下不能和http://ip:port/api/music 服务正常通信。
##[BUG] Android 端导入该音源，切歌后很快就提示换源失败，然后熄屏一段时间再打开程序有较大概率导致程序奔溃。
![微信图片_20241119155719](https://github.com/user-attachments/assets/5bd29327-76a1-4c28-ad44-3dd3f7ba7243)

### Lx Music 版本

1.7-beta.0

### 最后正常的版本

无可用版本

### 操作系统版本

Android 14

### 自定义音源
```js
/**
 * @name 测试音乐源
 * @description 我只是一个测试音乐源哦
 * @version 1.0.0
 * @author xxx
 * @homepage http://xxx
 */

const { EVENT_NAMES, request, on, send, utils, env, version } = globalThis.lx
const APIADDR = "http://168.168.0.130:18080/api/music"
const defaultHeaders={
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Content-Type': 'application/json',
}

const httpFetch = (url, options) => {
  return new Promise((resolve, reject) => {
    request(url, options, (err, resp) => {
      if (err) return reject(err)
      resolve(resp.body)
    })
  })
}


const musicUrl = async (source, { songmid }, quality) => {
    const url = await httpFetch(APIADDR, {
        method: 'GET',
        headers: defaultHeaders,
        body: JSON.stringify({
            "music_source": source,
            "id": songmid.toString() ,
            "quality": quality,
        }) 
    }).then((body) => {
        console.log(body.url)
        if (!body.url) {
            console.log("Failed to get music url.")  
            throw new Error('')
        }
        return body.url
    })
    return url;
}

const musicInfos = {
  tx: {
    name: '企鹅音乐',
    type: 'music',
    actions: ['musicUrl'],
    qualitys: ['128k', '320k', 'flac', 'flac24bit'],
  },
  wy: {
    name: '网易音乐',
    type: 'music',
    actions: ['musicUrl'],
    qualitys: ['128k', '320k', 'flac', 'flac24bit'],
  },
}

on(EVENT_NAMES.request, ({ source, action, info }) => {
  switch (action) {
    case 'musicUrl':
      return  musicUrl(source, info.musicInfo, info.type)
        .catch(err => Promise.reject(err))
    default:
      return Promise.reject('action not fond.')
  }
})

send(EVENT_NAMES.inited, {
  status: true,
  openDevTools: true,
  sources: musicInfos,
})
```

**Comment by lyswhut** [comment]
自定义源脚本的日志需要勾选下面的记录自定义源日志选项才会被记录，
息屏播放崩溃是软件被系统限制后台运行导致的，软件没有做保活处理，需要允许设置设备允许应用后台运行，如设置忽略省电优化之类的操作。

**Comment by 1qingfeng-1** [comment]
移动端勾选下面的记录自定义源日志选项，成功帮助我解决了这个问题。感谢！
解决问题的记录，给后来的人一些参考。
## 主要有两个问题
1. ‘GET’ 请求, HTTP/1.1协议规范里 对于 ‘GET’ 请求不支持在 body 里携带数据，参数只能通过URL传递，要么改为POST请求，要么get请求通过URL传递。
2. 移动端使用JSON.stringify({}） 传递的JSON字符串被双层引号包围，会导致解析问题，移动端直接写成
````js
body: {
            "music_source": source,
            "id": songmid,
            "quality": quality,
        },
### 修改上面两处，即改为POST请求，去掉JSON.stringify。我成功的在移动端和PC端打通了自定义音源。

**Comment by BenorX** [comment]
你好，我按照你的源也自己自己写了个服务端。请求QQ音乐，只能返回96kbps的音源，高音质的无法获取，可以指教下吗？
