### ISSUE TITLE
添加导入导出kwl格式歌单功能

### ISSUE THREAD

**Issue by gongkui** [lyswhut/lx-music-mobile#65]
**解决方案检查**
项目中搜索kwl格式，没有任何结果

**描述您想要的解决方案**
希望导入导出kwl格式的歌单

**描述您考虑过的替代方案**
目的是在洛雪中导入qq音乐歌单。目前开源库中可以导出qq音乐歌单的项目，导出的是kwl格式，如果能导入导出kwl格式歌单，则可以借助其他导出项目实现各平台歌单通用。

**Comment by lyswhut** [comment]
没听说过这个格式，这个格式的内容是怎么样的？

**Comment by gongkui** [comment]
不好意思，我是看到这个项目提到这个格式：
https://github.com/fengqiangboy/qq-music-list-to-kwl
但是最初没留意到项目说明已经失效，所以现在没有通用的歌单分享格式。

我尝试打开洛雪lxmc格式的歌单，发现不是文本编码。如果能提供文本编码的导入导出格式，我可以试试用以下项目导出歌单到对应格式。
https://github.com/timmy0209/PLEX-import-musiclist
https://github.com/keivenliao/QQ2NE

**Comment by lyswhut** [comment]
你可以将lxmc重命名成gz即可用压缩软件打开

**Comment by xueyitan** [comment]
这个问题有解决了么
