### ISSUE TITLE
建议添加歌曲排序功能和在播放界面直接删除歌曲功能

### ISSUE THREAD

**Issue by sunqixiao** [lyswhut/lx-music-mobile#66]

**Comment by lyswhut** [comment]
目前只有手动排序（调整位置），自动对整个列表排序后面再考虑添加

**Comment by lyswhut** [comment]
删除歌曲可以在外面的播放栏长按封面定位歌曲去删

**Comment by sunqixiao** [comment]
谢谢！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年12月25日 22:01
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [lyswhut/lx-music-mobile] 建议添加歌曲排序功能和在播放界面直接删除歌曲功能 (Issue #66)


删除歌曲可以在外面的播放栏长按封面定位歌曲去删

―
