### ISSUE TITLE
[Bug] Two default list names hardcoded in Simplified Chinese

### ISSUE THREAD

**Issue by 3gf8jv4dv** [lyswhut/lx-music-mobile#662]
*Afraid you've forgotten, I'd like to hear what you think.*

The two default list names are hardcoded in Simplified Chinese. Could this be fixed?

<details>
<summary>Preview</summary>
<img src="https://github.com/user-attachments/assets/b44f85b8-2b38-4799-a8a5-8b56bb96b1f1" alt="lx-music-mobile-default-lists-name" width="400"/>

</details>

_Originally posted by @3gf8jv4dv in https://github.com/lyswhut/lx-music-mobile/issues/659#issuecomment-2557298041_

**Comment by lyswhut** [comment]
Try the latest code

**Comment by lyswhut** [comment]
Try again, I renamed the translation file
