### ISSUE TITLE
希望能出一个lx的ipa版本

### ISSUE THREAD

**Issue by CCWAY** [lyswhut/lx-music-mobile#67]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

求一个ipa文件，🙏🙏🙏

### 描述你想要的解决方案

ipa文件不需要签名的那种，能自己使用apple账号签名就行

**Comment by lyswhut** [comment]
没有计划兼容苹果设备（至少目前是这样）
