### ISSUE TITLE
希望单曲循环时候也能切歌

### ISSUE THREAD

**Issue by lin6051** [lyswhut/lx-music-mobile#69]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望单曲循环时候也能切歌，目前是切回原歌曲

### 描述你想要的解决方案

希望切换到 列表 下一首

**Comment by lyswhut** [comment]
已在v0.12.0新增
