### ISSUE TITLE
更新后在WiFi环境下直连无法播放

### ISSUE THREAD

**Issue by kuro4869** [lyswhut/lx-music-mobile#7]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)

**描述错误**

**重现**
重现行为的步骤：
1.转到“ ...”
2.点击“ ....”
3.向下滚动到“ ....”
4.看到错误

**预期行为**

**截图**

**环境：**
  -操作系统及版本：[例如：Android 10]
  -软件安装包及版本：[例如：1.0.0 arm64-v8a]

**其他内容**

**Comment by kuro4869** [comment]
必须科学上网或者使用移动网络 pc端一切正常 安卓11 运营商 电信 我更新前没出现以下问题 所以我判断应该是更新之后出现的

**Comment by kuro4869** [comment]
机型 OPPO Reno ace

**Comment by lyswhut** [comment]
无法播放的问题看常见问题解决
