### ISSUE TITLE
[Feature]: 希望可以写个自定义缓存目录的功能

### ISSUE THREAD

**Issue by shuxiaokai** [lyswhut/lx-music-mobile#71]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

找不到缓存文件在哪里

### 描述你想要的解决方案

希望添加一个自定义缓存目录功能

### 描述你考虑过的替代方案

希望添加一个自定义缓存目录功能

**Comment by lyswhut** [comment]
为了减少不必要的权限申请，所以将缓存目录设置在APP私有目录，
并且缓存功能使用的是exoPlayer自带的缓存功能，其文件不是MP3格式的文件：
![image](https://user-images.githubusercontent.com/20365169/147460407-db6d2caa-3e98-4435-8e25-a5d35f3e6e8d.png)

**Comment by shuxiaokai** [comment]
我手机系统是Android11的，看不到这个目录

**Comment by lyswhut** [comment]
私有目录需要root权限才能看到

**Comment by shuxiaokai** [comment]
好的，十分感谢解答

**Comment by addition1** [comment]
> ### 解决方案检查
> 
> - [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
> - [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题
> 
> ### 问题描述
> 
> 导入的歌单在哪显示？
