### ISSUE TITLE
网易云歌单导入的时候加载不出来

### ISSUE THREAD

**Issue by China-Huanghe** [lyswhut/lx-music-mobile#76]
网易云歌单导入的时候加载不出来

**Comment by ameaninglessname** [comment]
是选的小芸音乐么

**Comment by China-Huanghe** [comment]
> 是选的小芸音乐么

![Screenshot_20220103-005622518.jpg](https://user-images.githubusercontent.com/77739994/147883221-16aa377e-f19f-46c3-88bb-5034c939f08a.jpg)
选的是网易音乐

**Comment by China-Huanghe** [comment]
我发现我收藏的歌单可以导入，但是我创建的<我喜欢的音乐>导入会失败

**Comment by lyswhut** [comment]
歌单导入问题看常见问题歌单导入部分
