### ISSUE TITLE
[Feature]: 希望出个机车版

### ISSUE THREAD

**Issue by yxzeyz** [lyswhut/lx-music-mobile#77]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

谢谢大佬无偿奉献，我电脑版一直在用，然后也第一时间用了移动板，然后现在把移动版下载到机车发现也能用，就是需要自己点开，点播放，这样感觉按钮什么的有点小。任性的想有个适应大屏的版本，最好机车版，打开软件自动播放什么的

### 描述你想要的解决方案

谢谢大佬无偿奉献，我电脑版一直在用，然后也第一时间用了移动板，然后现在把移动版下载到机车发现也能用，就是需要自己点开，点播放，这样感觉按钮什么的有点小。任性的想有个适应大屏的版本，最好机车版，打开软件自动播放什么的

**Comment by lyswhut** [comment]
精力有限，不打算专门针对机车开发一个版本

**Comment by spring59** [comment]
支持，出个车机版本吧

**Comment by zhongwen-4** [comment]
> 支持，出个车机版本吧

安卓版不是支持横屏了吗还要车机版干嘛

**Comment by spring59** [comment]
> > 支持，出个车机版本吧
> 
> 安卓版不是支持横屏了吗还要车机版干嘛

车载用啊，现在的车机屏幕比较大，安卓版兼容不太好，按钮不好操作

**Comment by Gao-le-le** [comment]
> 精力有限，不打算专门针对机车开发一个版本
为什么我车机安装提示解析包失败
