### ISSUE TITLE
[Feature]: 希望外语歌显示原版歌词

### ISSUE THREAD

**Issue by 8ctive** [lyswhut/lx-music-mobile#78]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

有些外语歌显示的是翻译过的歌词

### 描述你想要的解决方案

希望原版歌词优先，或者有切换选项

**Comment by lyswhut** [comment]
有没有翻译这取决于歌曲的官方平台，没有翻译的话尝试换一个平台看看
