### ISSUE TITLE
[Feature]: 在readme中添加构建教程

### ISSUE THREAD

**Issue by Pr0pHesyer** [lyswhut/lx-music-mobile#89]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

没有构建教程导致其它开发者构建时没有相关的构建环境

### 描述你想要的解决方案

在readme中添加添加构建环境

### 描述你考虑过的替代方案

使用构建脚步

**Comment by lyswhut** [comment]
可以先参考这个：https://github.com/lyswhut/lx-music-mobile/issues/36#issuecomment-981060751

**Comment by lyswhut** [comment]
已添加
