### ISSUE TITLE
[Feature]: 希望新增桌面端点击歌手名或歌曲名快速进行搜索定位。感谢大佬！

### ISSUE THREAD

**Issue by Sucgz** [lyswhut/lx-music-mobile#95]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

希望新增桌面端点击歌手名或歌曲名快速进行搜索定位。感谢大佬！

### 描述你想要的解决方案

1

### 描述你考虑过的替代方案

1

### 附加信息

1

**Comment by lyswhut** [comment]
没看懂你要搜索定位什么

**Comment by ameaninglessname** [comment]
> 没看懂你要搜索定位什么

应该是点击歌手名 跳转到 歌手页面
点击歌曲名 跳转到 歌曲页面
之类的
