### ISSUE TITLE
[Feature]: 添加【听歌识曲】功能

### ISSUE THREAD

**Issue by 1457384613gh** [lyswhut/lx-music-mobile#99]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

整合各音乐平台的【听歌识曲】功能，开发一款同样轻量的【洛雪识曲】apk。很多突然听到的不知名的歌曲名，可以立即打开app识别出来。

### 描述你想要的解决方案

开发全新的【洛雪识曲】apk，或者相关功能嵌入【洛雪音乐】

**Comment by AWEkn1** [comment]
你这想法可以.

**Comment by lyswhut** [comment]
重复：https://github.com/lyswhut/lx-music-desktop/issues/587
